Description of nbr2dir
Home > AbraVibe > nbr2dir.m
nbr2dir
PURPOSE
NBR2DIR Convert numeric direction to string
SYNOPSIS
function DirString = nbr2dir(DirNumber)
DESCRIPTION
 NBR2DIR   Convert numeric direction to string
       DirString = nbr2dir(DirNumber)
       DirString           String with e.g. 'X+' or '+X'
       DirNumber           Number +/- 1, 2, 3 for +/- X, Y, Z
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
modalchk MODALCHK Standard checks on FRF matrix for exp. modal analysis
unvr58 UNVR58 Read SDRC universal file test data record
unvrb58 UNV_RB58 Read a binary universal file record 58b
SOURCE CODE
function DirString = nbr2dir(DirNumber)
% NBR2DIR   Convert numeric direction to string
%
%       DirString = nbr2dir(DirNumber)
%
%       DirString           String with e.g. 'X+' or '+X'
%
%       DirNumber           Number +/- 1, 2, 3 for +/- X, Y, Z
%
% Copyright (c) 2009-2011 by Anders Brandt
% Email: abra@iti.sdu.dk
% Version: 1.0 2011-06-23
% This file is part of ABRAVIBE Toolbox for NVA
if DirNumber == 0
    DirString='';
elseif DirNumber == 1
    DirString='X+';
elseif DirNumber == -1
    DirString='X-';
elseif DirNumber == 2
    DirString='Y+';
elseif DirNumber == -2
    DirString='Y-';
elseif DirNumber == 3
    DirString='Z+';
elseif DirNumber == -3
    DirString='Z-';
end