Description of poles2fz
Home > AbraVibe > poles2fz.m
poles2fz
PURPOSE
POLES2FZ Convert poles to frequencies and relative damping
SYNOPSIS
function [fr,zr] = poles2fz(poles)
DESCRIPTION
POLES2FZ Convert poles to frequencies and relative damping
       [fr,zr] = poles2fz(poles)
       fr          Undamped natural (eigen-) frequencies, in vector
       zr          Relative damping ratios, in vector same length as fr
       poles       Complex poles in column vector
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
frf2msdof FRF2MSDOF Curve fit FRFs into poles and mode shapes, SDOF techniques
listpoles LISTPOLES List undamped natural frequencies and damping factors
plotmac PLOTMAC Plot Manhattan type MAC matrix plot
sdiagramGUI SDIAGRAMGUI MATLAB code for sdiagramGUI.fig. This is an internal function
wincomp WINCOMP Compensate poles due to exponential window from Impact testing
SOURCE CODE
function [fr,zr] = poles2fz(poles)
%POLES2FZ Convert poles to frequencies and relative damping
%
%       [fr,zr] = poles2fz(poles)
%
%       fr          Undamped natural (eigen-) frequencies, in vector
%       zr          Relative damping ratios, in vector same length as fr
%
%       poles       Complex poles in column vector
%
% Copyright (c) 2009-2011 by Anders Brandt
% Email: abra@iti.sdu.dk
% Version: 1.0 2011-06-23
% This file is part of ABRAVIBE Toolbox for NVA
a=real(poles);
b=imag(poles);
wr=sqrt(a.^2+b.^2);     % This is more transparent than the equivalent wr=abs(poles).^2
fr=1/2/pi*wr;
zr=-a./wr;