Description of winacf
Home > AbraVibe > winacf.m
winacf
PURPOSE
WINACF Calculate amplitude correction factor of time window
SYNOPSIS
function Aw = winacf(w);
DESCRIPTION
WINACF Calculate amplitude correction factor of time window
       Aw = winacf(win)
       Aw          Amplitude correction factor (=2 for Hanning window)
       w           Time window as column vector
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
acsdw ACSDW Calculate cross PSD from time data, Welch's method (standard)
alinspec ALINSPEC Calculate linear (rms) spectrum from time data
alinspecp ALINSPECP Calculate linear (rms) spectrum of time data, with phase
apsdw APSDW Calculate auto PSD from time data, Welch's method (standard)
time2xmtrxc TIME2XMTRXC Computes In-/Out cross spectral matrices from time data by cyclic averaging
SOURCE CODE
function Aw = winacf(w);
%WINACF Calculate amplitude correction factor of time window
%
%       Aw = winacf(win)
%
%       Aw          Amplitude correction factor (=2 for Hanning window)
%
%       w           Time window as column vector
% Copyright (c) 2009-2011 by Anders Brandt
% Email: abra@iti.sdu.dk
% Version: 1.0 2011-06-23
% This file is part of ABRAVIBE Toolbox for NVA
Aw=length(w)/sum(w);