Description of winenbw
Home > AbraVibe > winenbw.m
winenbw
PURPOSE
WINENBW Calculate equivalent noise bandwidth of time window
SYNOPSIS
function Be = winenbw(w);
DESCRIPTION
WINENBW Calculate equivalent noise bandwidth of time window
        Be = winenbw(w)
        Be         Normalized equivalent noise bandwidth (=1.5 for Hanning window)
        w          Time window in column vector
 See also   winacf ahann aflattop
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
acsdw ACSDW Calculate cross PSD from time data, Welch's method (standard)
apsdw APSDW Calculate auto PSD from time data, Welch's method (standard)
map2order MAP2ORDER Extract orders from RPM map, fix fs or synchronuous sampling
spec2noct SPEC2NOCT Calculate 1/n octave spectrum from an FFT spectrum
time2xmtrxc TIME2XMTRXC Computes In-/Out cross spectral matrices from time data by cyclic averaging
SOURCE CODE
function Be = winenbw(w);
%WINENBW Calculate equivalent noise bandwidth of time window
%
%        Be = winenbw(w)
%
%        Be         Normalized equivalent noise bandwidth (=1.5 for Hanning window)
%
%        w          Time window in column vector
%
% See also   winacf ahann aflattop
% Copyright (c) 2009-2011 by Anders Brandt
% Email: abra@iti.sdu.dk
% Version: 1.0 2011-06-23
% This file is part of ABRAVIBE Toolbox for NVA
Be=length(w)*sum(w.^2)/sum(w)^2;