Description of checksw
Home > AbraVibe > checksw.m
checksw
PURPOSE
CHECKSW Check if running MATLAB or GNU/Octave
SYNOPSIS
function sw = checksw
DESCRIPTION
 CHECKSW  Check if running MATLAB or GNU/Octave
       sw = checksw
       sw      'MATLAB' or 'OCTAVE' depending on what software checksw is
               called from. 0 is returned if neither MATLAB or Octave was
               found (unexpected).
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
aenvspec AENVSPEC Calculate envelope spectrum
plotreim PLOTREIM Plot real and imaginary part of complex function
plotrpmmapswf PLOTRPMMAPSWF Plot RPM map from synchronuous sampling in waterfall format
plotrpmmapwf PLOTRPMMAPWF Plot RPM map from fix fs in waterfall format
sdiagramnew SDIAGRAM Stability diagram, used for all methods (internal function)
tacho2rpm TACHO2RPM Extract rpm/time profile from tacho time signal
timediff TIMEDIFF Differentiate time signal
unvread UNVREAD Read a standard UNV file
SOURCE CODE
function sw = checksw
% CHECKSW  Check if running MATLAB or GNU/Octave
%
%       sw = checksw
%
%       sw      'MATLAB' or 'OCTAVE' depending on what software checksw is
%               called from. 0 is returned if neither MATLAB or Octave was
%               found (unexpected).
%
% Copyright (c) 2009-2011 by Anders Brandt
% Email: abra@iti.sdu.dk
% Version: 1.0 2011-06-23
%          1.1 2018-03-09 Changed procedure as very slow befor
% This file is part of ABRAVIBE Toolbox for NVA
% The platform is now established once and for all during the installation
% by running 'abrainst'
if exist('Platform.mat','file') == 2
    load('Platform')
else
    error('You have not installed ABRAVIBE. Please run the script ''abrainst'' in the Abravibe_Toolbox directory!')
end