function createfigure_Phasenlage_JM_v06(X1, X2, Drehzahl, Bezeichnung)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 13-May-2014 12:07:59

% Create figure
figure1 = figure;
 
% Create axes
 axes1 = axes('Parent',figure1);
%% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[-200 200]);
%% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes1,[-200 200]);
box(axes1,'on');
hold(axes1,'all');

string_Drehzahl_GL = strcat( 'Gleitlager', num2str(Drehzahl), 'U/min');
string_Drehzahl_WL = strcat( 'Waelzlager', num2str(Drehzahl), 'U/min');

% Create plot
plot(X1,'Parent',axes1,'DisplayName',string_Drehzahl_GL);
plot(X2, 'Parent', axes1, 'DisplayName', string_Drehzahl_WL);


% Create xlabel
xlabel('Re = x-Achse [N]');

% Create ylabel
ylabel('Im = y-Achse [N]');

Titel=strcat('Phasenlage ', num2str(Drehzahl), ' - ', Bezeichnung);

% Create title
title(Titel);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.171212302319417 0.348556375053687 0.11872528180689 0.0763077412953007]);

grid;


% Save Plot as .pdf JM
Dateiname = strcat('Diagramme\Phasenlagen_einzeln\Phasenlage_', Bezeichnung, '_', num2str(Drehzahl), '.pdf');
mkdir('Diagramme\Phasenlagen_einzeln');
print(figure1, '-dpdf', Dateiname);

close all;
