function createfigure_Kraftamplitude_Drehzahlen_Messung(X1, YMatrix1, Bezeichnung)
%CREATEFIGURE(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 04-Jun-2014 14:04:42

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
%% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[100 2000]);
%% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes1,[0 100]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1);
set(plot1(1),'DisplayName','Fmess GL Amplitude');
set(plot1(2),'DisplayName','Fmess WL Amplitude');

% Create xlabel
xlabel('Drehzahlen in U/min');

% Create ylabel
ylabel('Kräfteamplituden in Newton');

% Create title
title(['Unwuchtantwortkräfte über Drehzahl',sprintf('\n'),'Messung']);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.710158150851581 0.796747967479675 0.157846715328467 0.0731707317073171]);

grid;

% Save Plot as .pdf

Dateiname = strcat('Diagramme\Unwuchtantwort_Drehzahl\', Bezeichnung, '_.pdf');
mkdir('Diagramme\Unwuchtantwort_Drehzahl');
print(figure1, '-dpdf', Dateiname);

close all;

