Description of makexaxis
Home > AbraVibe > makexaxis.m
makexaxis
PURPOSE
MAKEXAXIS Create a time or frequency x axis
SYNOPSIS
function x = makexaxis(y,dx,x0);
DESCRIPTION
MAKEXAXIS Create a time or frequency x axis
           x = makexaxis(y,dx,x0);
           y       Y axis
           dx      x increment
           x0      Start x value (default = 0)
 This command can be used to create an x axis for time data as for example
 t=makexaxis(y,1/fs) if fs is the sampling frequency, and start is 0 sec.
 or for a spectrum by using
 f=makexaxis(Y,fs/N)
 if Y is a spectrum using blocksize N, starting at 0 Hz.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
abrabrowse ABRABROWSE GUI-based data browser for ABRAVIBE toolbox data files
apceps APCEPS Calculate power cepstrum of single-sided autospectrum
axcorrp AXCORRP Scaled cross-correlation between x (input) and y (output)
data2hmtrx DATA2HMTRX Import Abravibe FRF data into H matrix
frf2ir FRF2IR Convert freqency response(s) to impulse response(s)
impplot1 IMPPLOT1 Plot impact analysis plot with force/response. Internal
impsetup IMPSETUP Setup utility for IMPPROC
imptrig2 IMPTRIG2 Impact testing triggering and double impact detection
ir2ptime IR2PTIME Time domain MDOF methods for parameter extraction from free
plotfile PLOTFILE Plot data in ABRABIVE file(s) with default format
psd2time PSD2TIME Generate Gaussian random signal from PSD
synchsampr SYNCHSAMPR Resample data synchronously with RPM, using rpm-time profile
synchsampt SYNCHSAMPT Resample data synchronously with RPM, based on tacho signal
tacho2rpm TACHO2RPM Extract rpm/time profile from tacho time signal
timeint TIMEINT Integrate time signal
SOURCE CODE
function x = makexaxis(y,dx,x0);
%MAKEXAXIS Create a time or frequency x axis
%
%           x = makexaxis(y,dx,x0);
%
%           y       Y axis
%           dx      x increment
%           x0      Start x value (default = 0)
%
% This command can be used to create an x axis for time data as for example
% t=makexaxis(y,1/fs) if fs is the sampling frequency, and start is 0 sec.
% or for a spectrum by using
% f=makexaxis(Y,fs/N)
% if Y is a spectrum using blocksize N, starting at 0 Hz.
% Copyright (c) 2009-2011 by Anders Brandt
% Email: abra@iti.sdu.dk
% Version: 1.0 2011-06-23
% This file is part of ABRAVIBE Toolbox for NVA
%
if nargin == 2
    x0=0;
end
N=length(y);
x=(x0:dx:x0+(N-1)*dx)';