function h0=guiAbout(aniFig,SETUP);

bcolor=[1 1 1]*0.8;
pos = [250 100];
POS = get(aniFig,'Position');
h0=figure('Color'           ,bcolor, ...
   'MenuBar'                ,'none', ...
   'NumberTitle'            ,'off', ...
   'Name'                   ,'About', ...
   'Position'               ,[POS(1)+(POS(3)-pos(1))/2 POS(2)+(POS(4)-pos(2))/2 pos(1) pos(2)], ...
   'Resize'                 ,'off',...
   'Tag'                    ,'ANIMATE:ABOUT',...
   'CloseRequestFcn'        ,['command(''close'',''about'');']);

%icon    = imread(fullfile(SETUP.Path.Root,'ani.icon.bmp'));

% Text Pic
%h2=uicontrol('Parent',h0,...
%   'Units'                  , 'pixels',...
%   'Style'                  , 'toggle',...
%   'Position'               , [10 20 size(icon,2) size(icon,1)],...
%   'CData'                  , icon);
% Text Info
str = sprintf('Modal Vector Animation\nver. %s\n\nDan Lazor : UC-SDRL\n%s',SETUP.Version.Nr,SETUP.Version.Date);
h1=uicontrol('Parent',h0,...
   'Units'                  , 'pixels',...
   'Style'                  , 'Text',...
   'Position'               , [10 10 230 80],...
   'HorizontalAlignment'    , 'center',...
   'Backgroundcolor'        , [1 1 1]*0.8,...
   'String'                 , str);
