function h0=guiComponents(aniFig,SETUP,varargin);

bcolor=[1 1 1]*0.8;
pos = [300 300];
POS = get(aniFig,'Position');
if nargin>2
    POS = varargin{end};
else
    POS = [POS(1)+(POS(3)-pos(1))/2 POS(2)+(POS(4)-pos(2))/2 pos(1) pos(2)];
end
h0=figure('Color'           , bcolor, ...
   'MenuBar'                , 'none', ...
   'NumberTitle'            , 'off', ...
   'Name'                   , 'Components', ...
   'Position'               , POS, ...
   'Resize'                 , 'off',...
   'Tag'                    , 'ANIMATE:COMPONENTS',...
   'WindowButtonUpFcn'      , 'command(''components'',''stack'');',...
   'CloseRequestFcn'        , ['command(''close'',''components'');']);

% Listbox
h1  = uicontrol('Style'     , 'Text',...
    'Position'              , [10 pos(2)-22 pos(1)-20 17],...
    'backgroundcolor'       , bcolor,...
    'HorizontalAlignment'   , 'left',...
    'String'                , sprintf('Name       Vis Fill     Color'),...
    'FontName'              , 'Courier New');
h1  = uicontrol('Style'     , 'listbox',...
    'Position'              , [10 80 pos(1)-20 pos(2)-100],...
    'FontName'              , 'Courier New',...
    'Backgroundcolor'       , [1 1 1],...
    'Min'                   , -1,...
    'Max'                   , 1,...
    'Tag'                   ,'Component:Listbox',...
    'Callback'              ,'command(''components'',''select'');');

% Name
h1  = uicontrol('Style'     , 'Text',...
    'Position'              , [10 55 40 17],...
    'backgroundcolor'       , bcolor,...
    'String'                , 'Name');
h1  = uicontrol('Style'     , 'Edit',...
    'Position'              , [10 40 100 20],...
    'backgroundcolor'       , [1 1 1],...
    'String'                , '',...
    'Tag'                   ,'Component:Name',...
    'Callback'              ,'command(''components'',''name'');');
% Visible
h1  = uicontrol('Style'     , 'Checkbox',...
    'Position'              , [120 60 100 17],...
    'backgroundcolor'       , bcolor,...
    'String'                , 'Visible',...
    'Tag'                   ,'Component:Visible',...
    'Callback'              ,'command(''components'',''visible'');');
% Fill
h1  = uicontrol('Style'     , 'checkbox',...
    'Position'              , [120 40 100 20],...
    'backgroundcolor'       , bcolor,...
    'String'                , 'Fill',...
    'Tag'                   ,'Component:Fill',...
    'Callback'              ,'command(''components'',''fill'');');
% Fill color
h1  = uicontrol('Style'     , 'pushbutton',...
    'Position'              , [200 50 80 24],...
    'backgroundcolor'       , bcolor,...
    'String'                , 'Fill Color',...
    'Tag'                   ,'Component:FillColor',...
    'Callback'              ,'command(''components'',''fillColor'');');
% Wireframe
% Fill
h1  = uicontrol('Style'     , 'checkbox',...
    'Position'              , [100 10 100 20],...
    'backgroundcolor'       , bcolor,...
    'String'                , 'Wireframe',...
    'Tag'                   ,'Component:Wireframe',...
    'Callback'              ,'command(''components'',''wireframe'');');
% Close
h1  = uicontrol('Style'     , 'pushbutton',...
    'Position'              , [180 10 110 24],...
    'backgroundcolor'       , bcolor,...
    'String'                , 'Close',...
    'Tag'                   ,'Component:Close',...
    'Callback'              ,'command(''close'',''components'');');
