Description of command
Home > animate > command.m
command
PURPOSE
SYNOPSIS
function varargout = command(action,varargin)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
animate_fcn
command
defaults
guiAbout
guiComponents
guiPreferences
ufrw
vecompspace VECOMPSPACE
view3d Torsten Vogel 09.04.1999
This function is called by:
animate ANIMATE Animates wireframe models from universal files or MATLAB structure
animate_fcn
command
view3d Torsten Vogel 09.04.1999
SUBFUNCTIONS
function [VWS,CUV] = viewSetup(pV,pC,upVector)
function [ANI,Nodes]=set_mode(vector)
function HAND = getHandles(pos,ax,HAND,varargin);
function SETUP = updateRecentFiles(aniFig,file,type,SETUP);
function clr = getColor(default,msg);
function updatePrefs(action,dlg,TEMP)
function TEMP = getDefaults(TEMP);
function updateAniFig(aniFig,SETUP,H)
function str = compListbox(SETUP);
function UFF = createUFF(GEOMETRY,MODAL,SETUP,UFF);
SOURCE CODE
function varargout = command(action,varargin)
global SETUP MODAL GEOMETRY UDATA RESIZE UFF
aniFig  = findobj(0,'Tag','ANIMATE');
aniAxis = findobj(aniFig,'Tag','Axes:Single');
switch action
    case 'MaxDeflection'
        SETUP.Display.MaxDeflection=1;
    otherwise
        SETUP.Display.MaxDeflection=0;
end
switch action
    case 'initDefaults'
        varargout{1}    = getDefaults(SETUP);
    case 'run_animate'
        while get(findobj(aniFig,'Tag','Toggle:Animate'),'Value')
            animate_fcn;
            if ~ishandle(aniFig)
                return
            end
        end
    case 'components'
        dlg = findobj(0,'Tag','ANIMATE:COMPONENTS');
        if all([isempty(dlg),~strcmp(varargin{1},'init')])
            return
        end
        switch varargin{1}
            case 'init'
                if ishandle(dlg)
                    figure(dlg)
                    return;
                end
                if strcmp(SETUP.View.Type,'Red/Blue Glasses')
                    command('viewType','Single');
                end
                set(findobj(aniFig,'Tag','Menu:View:RedBlue'),'Enable','off');
                if length(varargin)<2
                    dlg     = guiComponents(aniFig,SETUP);
                else
                    dlg     = guiComponents(aniFig,SETUP,varargin{end});
                end
                % INIT GUI
                lbstr   = compListbox(SETUP);
                str = {'off','on'};
                set(findobj(dlg,'Tag','Component:Listbox')  ,'String',lbstr,'Value',1);
                set(findobj(dlg,'Tag','Component:Name')     ,'String',SETUP.Component.Name{1});
                set(findobj(dlg,'Tag','Component:Visible')  ,'Value' ,SETUP.Component.Visible(1));
                set(findobj(dlg,'Tag','Component:Fill')     ,'Value' ,SETUP.Component.Fill(1));
                set(findobj(dlg,'Tag','Component:Wireframe'),'Value' ,SETUP.Component.Wireframe);
                set(UDATA.Handles.Conn,'Visible',str{SETUP.Component.Wireframe+1});
                if SETUP.Component.Wireframe & SETUP.Display.Markers
                    set(UDATA.Handles.Markers,'Visible','on')
                else
                    set(UDATA.Handles.Markers,'Visible','off')
                end
                SETUP.Component.Open    = 1;
                command(action,'visible',find(SETUP.Component.Visible),1);
                command(action,'fill'   ,find(SETUP.Component.Fill),1);
                DATA    = get(aniAxis,'UserData');
                for comp=1:size(SETUP.Component.Name,1)
                    set(UDATA.Handles.Wire(comp,:),'XData',DATA.CompNodes(SETUP.Component.WireIndex{comp},1,UDATA.ActiveFrame),...
                        'YData',DATA.CompNodes(SETUP.Component.WireIndex{comp},2,UDATA.ActiveFrame),...
                        'ZData',DATA.CompNodes(SETUP.Component.WireIndex{comp},3,UDATA.ActiveFrame));
                    ind     = find(SETUP.Component.FillComps==comp);
                    for ii=1:length(ind)
                        set(UDATA.Handles.Fill(ind(ii),:),'XData',DATA.NODES(SETUP.Component.FillConn{ind(ii)},1,UDATA.ActiveFrame),...
                            'YData',DATA.NODES(SETUP.Component.FillConn{ind(ii)},2,UDATA.ActiveFrame),...
                            'ZData',DATA.NODES(SETUP.Component.FillConn{ind(ii)},3,UDATA.ActiveFrame));
                    end
                end
            case 'select'
                val = min(get(gcbo,'Value'));
                set(findobj(dlg,'Tag','Component:Name')     ,'String',SETUP.Component.Name{val});
                set(findobj(dlg,'Tag','Component:Visible')  ,'Value' ,SETUP.Component.Visible(val));
                set(findobj(dlg,'Tag','Component:Fill')     ,'Value' ,SETUP.Component.Fill(val));
            case 'name'
                str     = get(gcbo,'String');
                val     = get(findobj(dlg,'Tag','Component:Listbox'),'Value');
                if length(str)>10
                    str = str(1:10);
                end
                for ii=1:length(val)
                    SETUP.Component.Name{val(ii),1}  = str;
                end
                lbstr   = compListbox(SETUP);
                set(findobj(dlg,'Tag','Component:Listbox')  ,'String',lbstr);
                set(findobj(dlg,'Tag','Component:Name')     ,'String',SETUP.Component.Name{min(val)});
            case 'fill'
                str = {'off','on'};
                if nargin==2
                    val  = get(findobj(dlg,'Tag','Component:Listbox'),'Value');
                    onoff   = get(gcbo,'Value');
                    SETUP.Component.Fill(val,1)  = onoff;
                    lbstr   = compListbox(SETUP);
                    set(findobj(dlg,'Tag','Component:Listbox')  ,'String',lbstr);
                else
                    val     = varargin{2};
                    onoff   = varargin{3};
                end
                for ii=1:length(val)
                    ind = find(SETUP.Component.FillComps==val(ii));
                    set(UDATA.Handles.Fill(ind,:),'Visible',str{onoff+1});
                end
            case 'visible'
                if nargin==2
                    val  = get(findobj(dlg,'Tag','Component:Listbox'),'Value');
                    val     = get(findobj(dlg,'Tag','Component:Listbox'),'Value');
                    onoff   = get(gcbo,'Value');
                    SETUP.Component.Visible(val,:)  = onoff;
                    lbstr   = compListbox(SETUP);
                    set(findobj(dlg,'Tag','Component:Listbox')  ,'String',lbstr);
                else
                    val     = varargin{2};
                    onoff   = varargin{3};
                end
                str = {'off','on'};
                set(UDATA.Handles.Wire(val,:),'Visible',str{onoff+1});
                % enable labels
                if SETUP.Display.Labels & ~SETUP.Component.Wireframe
                    offInd  = find(~SETUP.Component.Visible);
                    onInd   = find( SETUP.Component.Visible);
                    indOff  = unique(setdiff([SETUP.Component.WireIndex{offInd}],length(UDATA.Handles.Labels)+1));
                    indOn   = unique(setdiff([SETUP.Component.WireIndex{onInd}] ,length(UDATA.Handles.Labels)+1));
                    set(UDATA.Handles.Labels(indOff,:),'Visible','off');
                    set(UDATA.Handles.Labels(indOn,:) ,'Visible','on');
                end
                %keyboard
                ostr    = str{all([SETUP.Display.Markers,SETUP.Component.Open])+1};
                set(UDATA.Handles.Mark(find(~SETUP.Component.Visible),:),'Visible','off');
                set(UDATA.Handles.Mark(find( SETUP.Component.Visible),:),'Visible',ostr);
            case 'fillColor'
                val     = get(findobj(dlg,'Tag','Component:Listbox'),'Value');
                clr     = getColor(SETUP.Component.Color(min(val),:),[SETUP.Component.Name{min(val)} ' fill color']);
                if isempty(clr)
                    return;
                end
                SETUP.Component.Color(val,:)    = ones(length(val),1)*clr;
                lbstr   = compListbox(SETUP);
                set(findobj(dlg,'Tag','Component:Listbox')  ,'String',lbstr);
                for comp=1:length(val)
                    set(UDATA.Handles.Wire(val(comp),:),'Color',clr);
                    set(UDATA.Handles.Mark(val(comp),:),'Color',clr);
                    for ii=1:length(val)
                        ind = find(SETUP.Component.FillComps==val(ii));
                        set(UDATA.Handles.Fill(ind,:),'FaceColor',clr);
                    end
                end
            case 'wireframe'
                str = {'off','on'};
                SETUP.Component.Wireframe = get(gcbo,'Value');
                set(UDATA.Handles.Conn,'Visible',str{SETUP.Component.Wireframe+1});
                if SETUP.Component.Wireframe & SETUP.Display.Labels
                    set(UDATA.Handles.Labels,'Visible','on');
                elseif SETUP.Display.Labels & ~SETUP.Component.Wireframe
                    offInd  = find(~SETUP.Component.Visible);
                    onInd   = find( SETUP.Component.Visible);
                    indOff  = unique(setdiff([SETUP.Component.WireIndex{offInd}],length(UDATA.Handles.Labels)+1));
                    indOn   = unique(setdiff([SETUP.Component.WireIndex{onInd}] ,length(UDATA.Handles.Labels)+1));
                    set(UDATA.Handles.Labels(indOff,:),'Visible','off');
                    set(UDATA.Handles.Labels(indOn,:) ,'Visible','on');
                end
                if SETUP.Component.Wireframe & SETUP.Display.Markers
                    set(UDATA.Handles.Markers,'Visible','on')
                else
                    set(UDATA.Handles.Markers,'Visible','off')
                end
            case 'stack'
                if ~strcmp(get(dlg,'SelectionType'),'open')
                    return
                end
                scrSize     = get(0         , 'ScreenSize');
                aniFigPos   = get(aniFig    , 'Position');
                dlgFigPos   = get(dlg       , 'Position');
                if aniFigPos(1)-dlgFigPos(3)-7>scrSize(1)
                    Xpos  = aniFigPos(1)-dlgFigPos(3)-7;
                elseif aniFigPos(1)+aniFigPos(3)+7+dlgFigPos(3)<scrSize(3);
                    Xpos  = aniFigPos(1)+aniFigPos(3)+7;
                else
                    Xpos  = aniFigPos(1)+aniFigPos(3)-dlgFigPos(3);
                end
                if aniFigPos(2)<scrSize(2)
                    Ypos  = aniFigPos(2)+aniFigPos(4)+10-dlgFigPos(4);
                elseif scrSize(4)-aniFigPos(4)<80
                    Ypos  = aniFigPos(2)+aniFigPos(4)-dlgFigPos(4)-75;
                else
                    Ypos  = aniFigPos(2)+aniFigPos(4)-dlgFigPos(4)+22;
                end
                set(dlg,'Position',[Xpos Ypos dlgFigPos(3) dlgFigPos(4)]);
        end
    case 'help'
        switch varargin{1}
            case 'help'
                if ~exist(fullfile(SETUP.Path.Root,'Help\animation.html'),'file')
                    [file,path] = uigetfile(fullfile(SETUP.Path.Root,'animation.html'),'Selected animation.html file...');
                    if file==0
                        return
                    end
                    SETUP.Path.Help = path;
                    defaults('addPaths',SETUP);
                end
                open(fullfile(SETUP.Path.Help,'\animation.html'));
            case 'about'
                guiAbout(aniFig,SETUP);
        end
    case 'updatePrefs'
        updatePrefs('all' ,findobj(0,'Tag','ANIMATE:PREFERENCES'),SETUP);
        set(findobj(0,'Tag','ANIMATE:PREFERENCES'),'Userdata',SETUP);
    case 'autoApplyPrefs'
        TEMP    = get(findobj(0,'Tag','ANIMATE:PREFERENCES'),'Userdata');
        updateAniFig(aniFig,TEMP,UDATA.Handles);
        SETUP.Animation = TEMP.Animation;
        SETUP.Display   = TEMP.Display;
        SETUP.View      = TEMP.View;
        SETUP.Colors    = TEMP.Colors;
        SETUP.AVI       = TEMP.AVI;
        SETUP.Snapshot  = TEMP.Snapshot;
        updatePrefs('all' ,findobj(0,'Tag','ANIMATE:PREFERENCES'),SETUP);
        set(findobj(0,'Tag','ANIMATE:PREFERENCES'),'Userdata',TEMP);
        command('reset_animation');
    case 'updateRotate'
        if strcmp(SETUP.View.Type,'Red/Blue Glasses')
            [AZ,EL] = view(aniAxis);
            ortho11 = findobj(aniFig,'Tag','Axes:Ortho11');
            set(ortho11,'View',[AZ,EL],'CameraUpVector',get(aniAxis,'CameraUpVector'));
            camorbit(ortho11, SETUP.View.CrosseyeAngle*2,0,'camera',SETUP.View.UpVector(2))
        end
    case 'preferences'
        dlg = findobj(0,'Tag','ANIMATE:PREFERENCES');
        if all([isempty(dlg),~strcmp(varargin{1},'init')])
            return
        end
        TEMP    = get(dlg,'Userdata');
        switch varargin{1}
            case 'autoapply'
                SETUP.Animation.AutoApplyPrefs  = get(gcbo,'Value');
                TEMP.Animation.AutoApplyPrefs   = get(gcbo,'Value');
            case 'update'
                updatePrefs('all' ,dlg,SETUP);
                set(dlg,'Userdata',SETUP);
            case 'init'
                if ishandle(dlg)
                    figure(dlg)
                    return;
                end
                prefFig = guiPreferences(aniFig,SETUP);
                set(prefFig,'Userdata',SETUP);
                verargout{1}    = prefFig;
                TEMP            = SETUP;
            case 'avi'
                switch varargin{2}
                    case 'Format'
                        str = get(gcbo,'String');
                        val = get(gcbo,'Value');
                        TEMP.AVI.Format = str{val};
                    case 'Quality'
                        val = abs(str2num(get(gcbo,'String')));
                        TEMP.AVI.Quality    = round(min([100,max([1,val])]));
                        set(gcbo,'String',num2str(TEMP.AVI.Quality));
                    case 'TimeLength'
                        TEMP.AVI.Quality    = abs(str2num(get(gcbo,'String')));
                        set(gcbo,'String',num2str(TEMP.AVI.TimeLength));
                    case 'DoAllModes'
                        TEMP.AVI.DoAllModes = get(gcbo,'Value');
                end
            case 'snapshot'
                switch varargin{2}
                    case 'Format'
                        str = get(gcbo,'String');
                        val = get(gcbo,'Value');
                        TEMP.Snapshot.Format    = str{val};
                    case 'Renderer'
                        str = get(gcbo,'String');
                        val = get(gcbo,'Value');
                        TEMP.Snapshot.Renderer  = str{val};
                    case 'Quality'
                        val = abs(str2num(get(gcbo,'String')));
                        TEMP.Snapshot.Quality   = round(min([100,max([1,val])]));
                        set(gcbo,'String',num2str(TEMP.Snapshot.Quality));
                    case 'Resolution'
                        TEMP.Snapshot.Resolution    = round(abs(str2num(get(gcbo,'String'))));
                        set(gcbo,'String',num2str(TEMP.Snapshot.Resolution));
                    case 'DoAllModes'
                        TEMP.Snapshot.DoAllModes    = get(gcbo,'Value');
                end
            case 'exportPath'
                switch varargin{2}
                    case 'edit'
                        dirStr  = get(gcbo,'String');
                        if exist(dirStr,'dir')~=7
                            resp = questdlg('%s\n\nDirectory does not exist.\nCreate it now?','Animation Warning','Yes','No','Yes');
                            if strcmp(resp,'No')
                                set(gcbo,'String',SETUP.Path.Export)
                                return;
                            else
                                mkdir(dirStr)
                            end
                        end
                        SETUP.Path.Export   = dirStr;
                    case 'push'
                        dirStr  = uigetdir(SETUP.Path.Export,'Choose the export directory...');
                        if dirStr == 0
                            return;
                        end
                        if exist(dirStr,'dir')~=7
                            resp = questdlg('%s\n\nDirectory does not exist.\nCreate it now?','Animation Warning','Yes','No','Yes');
                            if strcmp(resp,'No')
                                set(gcbo,'String',SETUP.Path.Export)
                                return;
                            else
                                mkdir(dirStr)
                            end
                        end
                        SETUP.Path.Export   = dirStr;
                        set(findobj(dlg,'Tag','Preferences:EditExportPath'),'String',SETUP.Path.Export)
                end
            case 'stack'
                if ~strcmp(get(dlg,'SelectionType'),'open')
                    return
                end
                scrSize     = get(0         , 'ScreenSize');
                aniFigPos   = get(aniFig    , 'Position');
                dlgFigPos   = get(dlg       , 'Position');
                if aniFigPos(1)-dlgFigPos(3)-7>scrSize(1)
                    Xpos  = aniFigPos(1)-dlgFigPos(3)-7;
                elseif aniFigPos(1)+aniFigPos(3)+7+dlgFigPos(3)<scrSize(3);
                    Xpos  = aniFigPos(1)+aniFigPos(3)+7;
                else
                    Xpos  = aniFigPos(1)+aniFigPos(3)-dlgFigPos(3);
                end
                if aniFigPos(2)<scrSize(2)
                    Ypos  = aniFigPos(2)+aniFigPos(4)+10-dlgFigPos(4);
                elseif scrSize(4)-aniFigPos(4)<80
                    Ypos  = aniFigPos(2)+aniFigPos(4)-dlgFigPos(4)-75;
                else
                    Ypos  = aniFigPos(2)+aniFigPos(4)-dlgFigPos(4)+22;
                end
                set(dlg,'Position',[Xpos Ypos dlgFigPos(3) dlgFigPos(4)]);
            case 'animation'
                val = str2num(get(gcbo,'String'));
                if isempty(val)
                    updatePrefs('animation',dlg,TEMP);
                    return;
                end
                switch varargin{2}
                    case 'FPC'
                        val = min([max([3,round(val)]),503]);
                        TEMP.Animation.Frames   = val;
                    case 'Amp'
                        val = min([max([0.01,round(val*100)/100]),100.01]);
                        TEMP.Animation.Amplitude = val;
                    case 'Deg'
                        val = min([max([-360,round(val)]),360]);
                        TEMP.Animation.Theta   = val;
                end
            case 'display'
                eval(['TEMP.Display.' varargin{2} '=~TEMP.Display.' varargin{2} ';']);
            case 'view'
                str = get(gcbo,'String');
                val = get(gcbo,'Value');
                eval(['TEMP.View.' varargin{2} '=str{val};']);
            case 'apply'
                updateAniFig(aniFig,TEMP,UDATA.Handles);
                SETUP.Animation = TEMP.Animation;
                SETUP.Display   = TEMP.Display;
                SETUP.View      = TEMP.View;
                SETUP.Colors    = TEMP.Colors;
                SETUP.AVI       = TEMP.AVI;
                SETUP.Snapshot  = TEMP.Snapshot;
                TEMP            = SETUP;
                updatePrefs('all',dlg,TEMP);
                command('reset_animation');
            case 'reset'
                TEMP    = getDefaults(TEMP);
                SETUP.Animation.AutoApplyPrefs  = TEMP.Animation.AutoApplyPrefs;
                updatePrefs('all' ,dlg,TEMP);
            case 'defaults'
                TEMP    = defaults('loadDefaults',SETUP);
                SETUP.Animation.AutoApplyPrefs  = TEMP.Animation.AutoApplyPrefs;
                updatePrefs('all' ,dlg,TEMP);
            case 'save'
                defaults('writeINI',TEMP);
            case 'color'
                clr = getColor(eval(['TEMP.Colors.' varargin{2}]),[varargin{2} ' Color']);
                if isempty(clr);return;end
                eval(['TEMP.Colors.' varargin{2} '=clr;']);
        end % END Preferences =============================================
        set(dlg,'Userdata',TEMP)
        updatePrefs(varargin{1},dlg,TEMP);
        if SETUP.Animation.AutoApplyPrefs
            command('autoApplyPrefs');
        end
    case 'viewType'
        if strcmp(SETUP.View.Type,varargin{1})
            return;
        end
        SETUP.View.Type = varargin{1};
        ortho11 = findobj(aniFig,'Tag','Axes:Ortho11');
        ortho21 = findobj(aniFig,'Tag','Axes:Ortho21');
        ortho22 = findobj(aniFig,'Tag','Axes:Ortho22');
        delete([ortho11,ortho21,ortho22]);
        POS     = get(aniFig,'Position');
        set(aniAxis,'Position',[20 20 POS(3)-40 POS(4)-135]);
        set(UDATA.Handles.Markers(1)    ,'Color',SETUP.Colors.Markers)
        set(UDATA.Handles.Labels(:,1)   ,'Color',SETUP.Colors.Labels)
        set(UDATA.Handles.Conn(1)       ,'Color',SETUP.Colors.Shape)
        set(UDATA.Handles.Static(1)     ,'Color',SETUP.Colors.Static)
        set(UDATA.Handles.UCS(1,:)      ,'Color',SETUP.Colors.UCS)
        switch varargin{1}
            case 'Single'
                val =[1 0 0 0];
                set(findobj(aniFig,'Tag','Menu:View:Single'),'checked','on');
                set(findobj(aniFig,'Tag','Menu:View:Quad')  ,'checked','off');
                HAND    = getHandles(1,aniAxis,UDATA.Handles,'empty');
            case 'Quad'
                val =[0 1 0 0];
                ortho11 = copyobj(aniAxis,aniFig);
                pos     = get(ortho11,'Position');
                set(ortho11,'Position',[pos(1) pos(2)+pos(4)/2 pos(3)/2 pos(4)/2],'Tag','Axes:Ortho11');
                set(findobj(ortho11,'Tag','Axis:Shape'),'Erasemode','normal')
                [VWS,CUV]   = viewSetup(1,1,SETUP.View.UpVector);
                set(ortho11,'View',VWS,'CameraUpVector',CUV)
                HAND    = getHandles(2,ortho11,[]);
                ortho21 = copyobj(aniAxis,aniFig);
                set(ortho21 ,'Position',[pos(1) pos(2) pos(3)/2 pos(4)/2],'Tag','Axes:Ortho21');
                set(findobj(ortho21,'Tag','Axis:Shape'),'Erasemode','normal')
                [VWS,CUV] = viewSetup(2,3,SETUP.View.UpVector);
                set(ortho21,'View',VWS,'CameraUpVector',CUV)
                HAND    = getHandles(3,ortho21,HAND);
                ortho22 = copyobj(aniAxis,aniFig);
                set(ortho22 ,'Position',[40+pos(1)+pos(3)/2 pos(2) pos(3)/2 pos(4)/2],'Tag','Axes:Ortho22');
                set(findobj(ortho22,'Tag','Axis:Shape'),'Erasemode','normal')
                [VWS,CUV] = viewSetup(3,4,SETUP.View.UpVector);
                set(ortho22,'View',VWS,'CameraUpVector',CUV)
                HAND    = getHandles(4,ortho22,HAND);
                set(aniAxis     ,'Position',[40+pos(1)+pos(3)/2 pos(2)+pos(4)/2 pos(3)/2 pos(4)/2]);
                set(findobj(aniAxis,'Tag','Axis:Shape'),'Erasemode','normal')
                [VWS,CUV] = viewSetup(1,2,SETUP.View.UpVector);
                set(aniAxis,'View',[135 35],'CameraUpVector',CUV)
                set(findobj(aniFig,'Tag','Menu:View:Single'),'checked','off');
                set(findobj(aniFig,'Tag','Menu:View:Quad')  ,'checked','on');
                HAND    = getHandles(1,aniAxis,HAND);
                delete(findobj(ortho11,'Tag','ContextMenu\Axes'))
                delete(findobj(ortho21,'Tag','ContextMenu\Axes'))
                delete(findobj(ortho22,'Tag','ContextMenu\Axes'))
            case 'Cross-eyed'
                val =[0 0 1 0];
                ortho11 = copyobj(aniAxis,aniFig);
                pos     = get(ortho11,'Position');
                set(ortho11,'Position',[20 20 pos(3)/2 pos(4)],'Tag','Axes:Ortho11');
                set(findobj(ortho11,'Tag','Axis:Shape'),'Erasemode','normal')
                HAND    = getHandles(2,ortho11,[]);
                set(aniAxis     ,'Position',[40+pos(1)+pos(3)/2 pos(2) pos(3)/2 pos(4)]);
                set(findobj(aniAxis,'Tag','Axis:Shape'),'Erasemode','normal')
                HAND    = getHandles(1,aniAxis,HAND);
                camorbit(ortho11, SETUP.View.CrosseyeAngle,0,'camera',SETUP.View.UpVector(2))
                camorbit(aniAxis,-SETUP.View.CrosseyeAngle,0,'camera',SETUP.View.UpVector(2))
            case 'Red/Blue Glasses'
                val =[0 0 0 1];
                dPos    = get(aniAxis,'Position');
                ortho11 = copyobj(aniAxis,aniFig);
                pos     = get(ortho11,'Position');
                set(ortho11,'Position',dPos-[-5 0 0 0],'Tag','Axes:Ortho11');
                set(findobj(ortho11,'Tag','Axis:Shape'),'Erasemode','normal')
                HAND    = getHandles(2,ortho11,[]);
                chld    = get(ortho11,'Children');
                chld    = setdiff(chld,[HAND.Wire(:,2);HAND.Fill(:,2)]);
                set(chld,'Color',SETUP.Colors.RightEye);
                set(aniAxis     ,'Position',dPos+[5 0 0 0]);
                set(findobj(aniAxis,'Tag','Axis:Shape'),'Erasemode','normal')
                HAND    = getHandles(1,aniAxis,HAND);
                chld    = get(aniAxis,'Children');
                pchld   = findobj(aniAxis,'Type','Patch');
                chld    = setdiff(chld,[HAND.Wire(:,1);HAND.Fill(:,1)]);
                set(chld,'Color',SETUP.Colors.LeftEye);
                camorbit(ortho11, SETUP.View.CrosseyeAngle*2,0,'camera',SETUP.View.UpVector(2))
                camorbit(aniAxis,-SETUP.View.CrosseyeAngle*2,0,'camera',SETUP.View.UpVector(2))
        end
        str = {'off','on'};
        set(findobj(aniFig,'Tag','Menu:View:Single')    ,'Checked',str{val(1)+1});
        set(findobj(aniFig,'Tag','Menu:View:Quad')      ,'Checked',str{val(2)+1});
        set(findobj(aniFig,'Tag','Menu:View:Crosseyed') ,'Checked',str{val(3)+1});
        set(findobj(aniFig,'Tag','Menu:View:RedBlue')   ,'Checked',str{val(4)+1});
        UDATA.Handles.Markers   = HAND.Markers;
        UDATA.Handles.Labels    = HAND.Labels;
        UDATA.Handles.Conn      = HAND.Conn;
        UDATA.Handles.Static    = HAND.Static;
        UDATA.Handles.UCS       = HAND.UCS;
        UDATA.Handles.Wire      = HAND.Wire;
        UDATA.Handles.Fill      = HAND.Fill;
        UDATA.Handles.Mark      = HAND.Mark;
        if nargin<3;command('updatePrefs');end
    case 'Save'
        switch varargin{1}
            case 'Matlab'
                [file,path]=uiputfile([SETUP.Path.Data '*.mat'],'Export Matlab file...');
                if any([file==0,path==0])
                    path=[];file=[];
                    return;
                end
%                 [path,file,ext] = fileparts(fullfile(path,[file ext]));
                % Modified ABRA 18/2 -10: ext was not defined
                [path,file,ext] = fileparts(fullfile(path,[file]));
                save(fullfile(path,[file ext]),'GEOMETRY','MODAL');
                % Modified ABRA 18/2 -10: said = p, changed to path
                SETUP.Path.Data = path;
                SETUP   = updateRecentFiles(aniFig,fullfile(path,[file ext]),varargin{1},SETUP);
                defaults('addRecentFiles',SETUP);
            case 'UFF'
                [file,path]=uiputfile(fullfile(SETUP.Path.Data,'*.ufb'),'Export UFF binary file...');
                if any([file==0,path==0])
                    path=[];file=[];
                    return;
                end
                [p,n,e] = fileparts(fullfile(path,file));
                if ~strcmp(e,'.ufb')
                    file = [file '.ufb'];
                end
                % Headers
                for ii=1:length(UFF.dsn151)
                    uf{ii,1}    = UFF.DATA{UFF.dsn151(ii)};
                end
                % Units
                uf{end+1,1}     = UFF.DATA{min(UFF.dsn164)};
                % Nodes
                for ii=1:length(UFF.dsn15)
                    uf{end+1,1} = UFF.DATA{UFF.dsn15(ii)};
                    for node=1:length(uf{end}.Node)
                        uf{end}.Node(node).dispCS   = 0;
                    end
                end
                % Wireframe
                clrTable    = [0 0 0 ;10 10 10;1 0 0;0 1 0;0 0 1;0 1 1;1 0 1;1 1 0];
                for ii=1:length(UFF.dsn82)
                    clr = find(ismember(clrTable,SETUP.Component.Color(ii,:),'rows'))-1;
                    if isempty(clr)
                        % find closes
                        lst     = (clrTable-ones(8,1)*SETUP.Component.Color(1,:)).^2;
                        lstInd1 = find(min(lst(:,1))==lst(:,1));
                        lstInd2 = find(min(lst(:,2))==lst(:,2));
                        lstInd3 = find(min(lst(:,3))==lst(:,3));
                        rms     = sqrt(sum((clrTable-ones(8,1)*SETUP.Component.Color(1,:)).^2,2));
                        rmsInd  = find(min(rms)==rms);
                        ind     = [lstInd1;lstInd2;lstInd3;rmsInd];
                        uInd    = unique(ind);
                        for jj=1:length(uInd)
                            val(jj) = length(find(uInd(ii)==ind));
                        end
                        clr = uInd(min(find(max(val)==val)));
                        if isempty(clr)
                            clr = 0;
                        end
                    end
                    UFF.DATA{UFF.dsn82(ii)}.Color   = clr;
                    UFF.DATA{UFF.dsn82(ii)}.ID      = SETUP.Component.Name{ii};
                    uf{end+1,1} = UFF.DATA{UFF.dsn82(ii)};
                end
                % Modes
                for ii=1:length(MODAL)
                    base        = UFF.DATA{UFF.dsn55(ii)}; % 2012-01-13: bug fix changed 1 to ii so it goes through the modes. from 1 to ii.
                    uf{end+1,1} = base;
                    uf{end,1}.UID   = [];
                    uf{end,1}.Real  = [real(MODAL(ii).Freq) imag(MODAL(ii).Freq) 0 0 0 0]*2*pi;
                    for node=1:length(MODAL(ii).Nodes)
                        NODE(node,1).Num    = MODAL(ii).Nodes(node);
                        NODE(node,1).Data   = MODAL(ii).Data(node,:);
                    end
                    uf{end,1}.Node  = NODE;
                end
                file    = fullfile(p,file);
                ufrw('save',file,uf,'binary');
                SETUP   = updateRecentFiles(aniFig,file,varargin{1},SETUP);
                defaults('addRecentFiles',SETUP);
            case 'Snapshot'
                str     = {'BMP monochrome';'BMP 24-bit';'EMF metafile';'EPS b&w';'EPS color';'EPS2 B&W';'EPS2 color';'JPEG 24-bit';'PCX 24-bit';'PDF color';'PNG 24-bit';'TIFF 24-bit'};
                eqv     = {'-dbmpmono';'-dbmp';'-dmeta';'-deps';'-depsc';'-deps2';'-depsc2';'-djpeg';'-dpcx24b';'-dpdf';'-dpng';'-dtiff'};
                xtn     = {'bmp';'bmp';'emf';'eps';'eps';'eps';'eps';'jpg';'pcx';'pdf';'png';'tif'};
                type    = find(ismember(str,SETUP.Snapshot.Format));
                str     = {'Z-buffer';'Open GL';'Painters'};
                rnd     = {'-zbuffer';'-opengl';'-painters'};
                rndType = find(ismember(str,SETUP.Snapshot.Renderer));
                if ~SETUP.Snapshot.DoAllModes
                    % Save current mode only
                    [file,path]=uiputfile(fullfile(SETUP.Path.Export,['*.' xtn{type}]),'Save snapshot...');
                    if any([file==0,path==0])
                        path=[];file=[];
                        return;
                    end
                    [path,file,ext]     = fileparts(fullfile(path,file));
                    if isempty(ext)
                        ext = xtn{type};
                    end
                    SETUP.Path.Export   = path;
                    fileName            = fullfile(path,[file ext]);
                    set(gcf,'PaperPositionMode','auto')
                    print(aniFig,['-r' num2str(SETUP.Snapshot.Resolution)],eqv{type},rnd{rndType},fileName)
                else
                    resp    = questdlg('Are you ready to save all modes to snapshots?','Snapshot Warning','Yes','No','No');
                    if strcmp(resp,'No')
                        return;
                    end
                    for mode = 1:length(MODAL);
                        set(findobj(gcf,'Tag','popup_modeList'),'Value',mode);
                        command('update_mode');
                        % Do AVI
                        fname       = sprintf('Mode%02d(%4.4fHz).%s',mode,imag(MODAL(mode).Freq),xtn{type});
                        fileName    = fullfile(SETUP.Path.Export,fname);
                        % Turn on toggle
                        set(findobj(aniFig,'Tag','Toggle:Animate'),'Value',1);
                        SETUP.Display.MaxDeflection   = 1;
                        retVal  = 1;
                        drawnow;
                        UDATA.ActiveFrame   = SETUP.Animation.MaxFrame-1;
                        while retVal
                            retVal  = animate_fcn;
                        end
                        set(aniFig,'InvertHardcopy','off');
                        print(aniFig,['-r' num2str(SETUP.Snapshot.Resolution)],eqv{type},rnd{rndType},fileName);
                        set(findobj(aniFig,'Tag','Toggle:Animate'),'Value',0);
                    end
                end
            case 'AVI'
                if ~SETUP.AVI.DoAllModes
                    % Save current mode only
                    [file,path]=uiputfile(fullfile(SETUP.Path.Data,'*.avi'),'Save AVI file...');
                    if any([file==0,path==0])
                        path=[];file=[];
                        return;
                    end
                    try
                        [path,file,ext] = fileparts(fullfile(path,file));
                        fileName    = fullfile(path,[file ext]);
                        if length(fileName)>64
                            str = sprintf('AVI filenames are limited\nto a total length of 64 characters\n\n%s\n length = %d\n\nNot saving AVI.',fileName,length(fileName))
                            warndlg(str,'AVI Warning')
                            SETUP.AVI.On    = 0;
                            SETUP.AVI.Start = 0;
                            SETUP.AVI.Frame = 0;
                            SETUP.AVI.Movie = [];
                            return;
                        end
                        SETUP.AVI.FileName  = fileName;
                        SETUP.AVI.On        = 1;
                        UDATA.ActiveFrame   = floor(SETUP.Animation.Frames);
                        UDATA.Direction     = 1;
                        drawnow;
                        if ~get(findobj(aniFig,'Tag','Toggle:Animate'),'Value')
                            set(findobj(aniFig,'Tag','Toggle:Animate'),'Value',1);
                            command('run_animate')
                        end
                    catch
                        warndlg(lasterr,'Animation')
                        set(findobj(aniFig,'Tag','Toggle:Animate'),'Value',0);
                        SETUP.AVI.On    = 0;
                        SETUP.AVI.Start = 0;
                        SETUP.AVI.Frame = 0;
                        SETUP.AVI.Movie = [];
                    end
                else
                    % Save all modes
                    resp    = questdlg('Are you ready to save all modes to AVI?','AVI Warning','Yes','No','No');
                    if strcmp(resp,'No')
                        return;
                    end
                    for mode = 1:length(MODAL);
                        set(findobj(gcf,'Tag','popup_modeList'),'Value',mode);
                        command('update_mode');
                        % Do AVI
                        fname   = sprintf('Mode%02d(%4.4fHz).avi',mode,imag(MODAL(mode).Freq));
                        SETUP.AVI.FileName  = fullfile(SETUP.Path.Export,fname);
                        % Turn on toggle
                        set(findobj(aniFig,'Tag','Toggle:Animate'),'Value',1);
                        SETUP.AVI.On        = 1;
                        retVal              = 1;
                        UDATA.ActiveFrame   = floor(SETUP.Animation.Frames);
                        UDATA.Direction     = 1;
                        drawnow;
                        while retVal
                            retVal  = animate_fcn;
                        end
                        set(findobj(aniFig,'Tag','Toggle:Animate'),'Value',0);
                    end
                end
        end
        if ishandle(findobj(0,'Tag','ANIMATE:PREFERENCES'))
            set(findobj(findobj(0,'Tag','ANIMATE:PREFERENCES'),'Tag','Preferences:EditExportPath'),'String',SETUP.Path.Export);
        end
        defaults('addRecentFiles',SETUP);
    case 'zoom'
        val = get(varargin{1},'Value');
        if val
            set(findobj(aniFig,'Tag','Toggle:Rotate'),'Value',0);
            view3d zoom;
        else
            view3d off;
        end
    case 'rotate'
        val = get(varargin{1},'Value');
        if val
            set(findobj(aniFig,'Tag','Toggle:Zoom'),'Value',0);
            view3d rot;
        else
            view3d off;
        end
    case 'set'
        switch varargin{1}
            case 'FPC'
                switch varargin{2}
                    case 'edit'
                        val = round(str2num(get(gcbo,'String')));
                        if isempty(val)
                            set(gcbo,'String',num2str(SETUP.Animation.Frames));
                            set(findobj(aniFig,'Tag','Slider:FPC'),'Value',SETUP.Animation.Frames);
                            return
                        end
                    case 'slider'
                        val = round(get(gcbo,'Value'));
                end
                SETUP.Animation.Frames  = min([max([3,val]),503]);
                set(findobj(aniFig,'Tag','Edit:FPC')    , 'String',num2str(SETUP.Animation.Frames));
                set(findobj(aniFig,'Tag','Slider:FPC')  , 'Value',SETUP.Animation.Frames);
                command('reset_animation');
            case 'amp'
                switch varargin{2}
                    case 'edit'
                        val = round(str2num(get(gcbo,'String'))*100)/100;
                        if isempty(val)
                            set(gcbo,'String',num2str(SETUP.Animation.Amplitude));
                            set(findobj(aniFig,'Tag','Slider:Amp'),'Value',SETUP.Animation.Amplitude);
                            return
                        end
                    case 'slider'
                        val = round(get(gcbo,'Value')*100)/100;
                end
                SETUP.Animation.Amplitude   = min([max([.01,val]),100.01]);
                set(findobj(aniFig,'Tag','Edit:Amp')    , 'String',num2str(SETUP.Animation.Amplitude));
                set(findobj(aniFig,'Tag','Slider:Amp')  , 'Value',SETUP.Animation.Amplitude);
                command('reset_animation');
            case 'deg'
                switch varargin{2}
                    case 'edit'
                        val = round(str2num(get(gcbo,'String')));
                        if isempty(val)
                            set(gcbo,'String',num2str(SETUP.Animation.Theta));
                            set(findobj(aniFig,'Tag','Slider:Deg'),'Value',SETUP.Animation.Theta);
                            return
                        end
                    case 'slider'
                        val = round(get(gcbo,'Value'));
                end
                SETUP.Animation.Theta   = min([max([-360,val]),360]);
                set(findobj(aniFig,'Tag','Edit:Deg')    , 'String',num2str(SETUP.Animation.Theta));
                set(findobj(aniFig,'Tag','Slider:Deg')  , 'Value',SETUP.Animation.Theta);
                command('reset_animation');
        end % END set
        %if nargin<3;command('updatePrefs');end
        command('updatePrefs')
    case 'Change'
        str     = {'off','on'};
        if nargin<3;
            eval(['SETUP.Display.' varargin{1} '=~SETUP.Display.' varargin{1} ';']);
            value   = eval(['SETUP.Display.' varargin{1} ';']);
            command('updatePrefs');
        else
            value   = varargin{2};
            eval(['SETUP.Display.' varargin{1} '=value;']);
        end
        set(findobj(aniFig,'Tag',['Menu:Display:' varargin{1}]),'Checked',str{value+1});
        command('on/off',varargin{1});
    case 'MultipleChange'
        str     = {'off','on'};
        switch varargin{1}
            case {'Real','Imaginary','Complex'}
                option  = {'Real','Imaginary','Complex'};
                value   = strcmp(option,varargin{1});
                SETUP.View.VectorType = option{find(value==1)};
            case {'+X','+Y','+Z'}
                option  = {'+X','+Y','+Z'};
                vectors = eye(3);
                value   = strcmp(option,varargin{1});
                SETUP.View.UpVector = option{find(value==1)};
                switch SETUP.View.Type
                    case 'Single'
                        view(aniAxis,[1,1])
                        set(aniAxis,'CameraUpVector',vectors(find(value==1),:));
                    case {'Cross-eyed','Red/Blue Glasses'}
                        view(aniAxis,[1,1])
                        set(aniAxis,'CameraUpVector',vectors(find(value==1),:));
                        set(findobj(aniFig,'Tag','Axes:Ortho11'),'CameraUpVector',vectors(find(value==1),:))
                    case 'Quad'
                        view(aniAxis,[1,1])
                        set(aniAxis,'CameraUpVector',vectors(find(value==1),:));
                        [VWS,CUV]   = viewSetup(1,1,SETUP.View.UpVector);
                        set(findobj(aniFig,'Tag','Axes:Ortho11'),'View',VWS,'CameraUpVector',CUV)
                        [VWS,CUV]   = viewSetup(2,3,SETUP.View.UpVector);
                        set(findobj(aniFig,'Tag','Axes:Ortho21'),'View',VWS,'CameraUpVector',CUV)
                        [VWS,CUV]   = viewSetup(3,4,SETUP.View.UpVector);
                        set(findobj(aniFig,'Tag','Axes:Ortho22'),'View',VWS,'CameraUpVector',CUV)
                end
        end
        for ii=1:length(option)
            set(findobj(aniFig,'Tag',['Menu:View:' option{ii}]),'Checked',str{value(ii)+1});
        end
        command('reset_animation');
        command('changeView')
        if nargin<3;command('updatePrefs');end
    case 'on/off'
        str     = {'off','on'};
        switch varargin{1}
            case 'Annotate'
                set(findobj(aniFig,'Tag','Text:Annotate'),'Visible',str{SETUP.Display.Annotate+1});
            case 'Static'
                set(UDATA.Handles.Static,'Visible',str{SETUP.Display.Static+1});
            case 'Labels'
                set(UDATA.Handles.Labels,'Visible',str{SETUP.Display.Labels+1});
            case 'Markers'
                set(UDATA.Handles.Markers,'Visible',str{SETUP.Display.Markers+1});
            case 'UCS'
                set(UDATA.Handles.UCS,'Visible',str{SETUP.Display.UCS+1});
        end
        if SETUP.Component.Open
            command('components','visible',find(SETUP.Component.Visible),1);
            if ~SETUP.Component.Wireframe
                set(UDATA.Handles.Markers,'Visible','off');
            end
        end
        if nargin<3;command('updatePrefs');end
    case 'reset_animation'
        MAX=max(max(abs(MODAL(SETUP.Animation.ModeNr).Data)))./SETUP.Animation.Amplitude;
        vector.x=MODAL(SETUP.Animation.ModeNr).Data(:,1)./MAX;
        vector.y=MODAL(SETUP.Animation.ModeNr).Data(:,2)./MAX;
        vector.z=MODAL(SETUP.Animation.ModeNr).Data(:,3)./MAX;
        [ANIMATION,NODES]=set_mode(vector);
        % Set Axis Limits
        maxX    = max(max([ANIMATION.X]));
        maxY    = max(max([ANIMATION.Y]));
        maxZ    = max(max([ANIMATION.Z]));
        scl     = 0.01;
        maxX    = maxX*(1+sign(maxX)*scl);
        maxY    = maxY*(1+sign(maxX)*scl);
        maxZ    = maxZ*(1+sign(maxX)*scl);
        minX=min(min([ANIMATION.X]));
        minY=min(min([ANIMATION.Y]));
        minZ=min(min([ANIMATION.Z]));
        minX    = minX*(1-sign(minX)*scl);
        minY    = minY*(1-sign(minX)*scl);
        minZ    = minZ*(1-sign(minX)*scl);
        X   = [minX maxX];
        Y   = [minY maxY];
        Z   = [minZ maxZ];
        if diff(X)==0 | max(isnan(X))
            X   = [min(min([ANIMATION.X])) max(max([ANIMATION.X]))]+[-1e-8 1e-8];
        end
        if diff(Y)==0 | max(isnan(Y))
            Y   = [min(min([ANIMATION.Y])) max(max([ANIMATION.Y]))]+[-1e-8 1e-8];
        end
        if diff(Z)==0 | max(isnan(Z))
            Z   = [min(min([ANIMATION.Z])) max(max([ANIMATION.Z]))]+[-1e-8 1e-8];
        end
        % MATLAB Version changes
        axs = findobj(aniFig,'Type','Axes');
        for ii=1:length(axs)
            %axis(aniAxis,[minX maxX minY maxY minZ maxZ])
            set(axs(ii),'Xlim',X,'Ylim',Y,'Zlim',Z)
        end
    case 'geo/con'  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        warning off;
        set(aniAxis,'CameraViewAngleMode','auto');
        ii=0;
        delete(get(aniAxis,'Children'));
        axis(aniAxis,[-1 1 -1 1 -1 1]);
        hold on
        temp=1:length(GEOMETRY.node);
        ind=temp(ismember(GEOMETRY.node,unique(GEOMETRY.conn(~isnan(GEOMETRY.conn)))));
        for i=1:length(ind)
            DATA.PNodes(i,1)= GEOMETRY.node(ind(i));
            DATA.Plot(i,1)  = GEOMETRY.x(ind(i));
            DATA.Plot(i,2)  = GEOMETRY.y(ind(i));
            DATA.Plot(i,3)  = GEOMETRY.z(ind(i));
            DATA.Text(i,1)  = text(DATA.Plot(i,1),DATA.Plot(i,2),DATA.Plot(i,3),[' ' num2str(GEOMETRY.node(ind(i)))]);
            labelText(i,1)  = GEOMETRY.node(ind(i));
            set(DATA.Text(i,1),'Color',SETUP.Colors.Labels,'erasemode','normal','Fontsize',7,'Tag','Axis:Label');  % Text color is black
        end
        view(aniAxis,[135 35]);
        % Use single plot command to plot node markers and make markers light purple
        DATA.Plot(end+1,:)=[NaN NaN NaN];
        DATA.Point(1,1)=plot3(DATA.Plot(:,1),DATA.Plot(:,2),DATA.Plot(:,3),'.');
        set(DATA.Point,'Color',SETUP.Colors.Markers,'erasemode','normal','MarkerSize',5,'Tag','Axis:Node'); % Black Lines
        hold off
        conn=[];
        for ii=1:length(GEOMETRY.conn);
            if isnan(GEOMETRY.conn(ii))
                conn(ii)=length(DATA.Plot);
            else
                conn(ii)=find(DATA.PNodes==GEOMETRY.conn(ii));
            end
        end
        static_handle=line(DATA.Plot(conn,1),DATA.Plot(conn,2),DATA.Plot(conn,3),'Erasemode','normal','Color',SETUP.Colors.Static,'LineStyle','-','Tag','Axis:Static');
        conn_handle  =line(DATA.Plot(conn,1),DATA.Plot(conn,2),DATA.Plot(conn,3),'Erasemode','normal','Color',SETUP.Colors.Shape,'Tag','Axis:Shape');
        UDATA.ConnList=conn;
        %=================================================
        %=================================================
        SETUP.Component.Handle=[];
        compInd     = [];
        fillHand    = [];
        SETUP.Component.FillHandle      = [];
        SETUP.Component.FillComps       = [];
        SETUP.Component.FillConn        = [];
        connData                        = [];
        for comp=1:size(SETUP.Component.Name,1)
            CONN    = SETUP.Component.Nodes{comp,1};
            conn    = [];
            for ii=1:length(CONN);
                if isnan(CONN(ii))
                    conn(ii)=length(DATA.Plot);
                else
                    conn(ii)=find(DATA.PNodes==CONN(ii));
                end
            end
            ind = find(conn==max(conn));
            if ind(1)~=1
                ind     = [1 ind];
                conn    = [max(conn) conn];
            end
            ind = find(conn==max(conn));
            if ind(end)~=length(conn)
                ind     = [ind length(conn)+1];
                conn    = [conn max(conn)];
            end
            set(gca,'NextPlot','add');
            fillHand    = [];
            fillInd     = [];
            for ii=1:length(ind)-1
                connList            = conn(ind(ii)+1:ind(ii+1)-1);
                fillInd             = [fillInd;connList.'];
                fill_handle         = fill3(DATA.Plot(connList,1),DATA.Plot(connList,2),DATA.Plot(connList,3),SETUP.Component.Color(comp,:));
                fillHand            = [fillHand;fill_handle];
                compInd             = [compInd;1*comp];
                connData{end+1,1}   = connList;
                set(fill_handle,'Edgecolor',SETUP.Colors.Shape,'Erasemode','normal','Tag','Axis:Fill','visible','off');
            end
            SETUP.Component.MarkHandle(comp,1)  = plot3(DATA.Plot(conn,1),DATA.Plot(conn,2),DATA.Plot(conn,3),'.','Color',SETUP.Component.Color(comp,:),'Erasemode','normal','Tag','Axis:Mark','Visible','off','MarkerSize',5);
            SETUP.Component.WireHandle(comp,1)  = line( DATA.Plot(conn,1),DATA.Plot(conn,2),DATA.Plot(conn,3)    ,'Color',SETUP.Component.Color(comp,:),'Erasemode','normal','Tag','Axis:Wire','Visible','off');
            SETUP.Component.WireIndex{comp,1}   = conn;
            SETUP.Component.FillHandle          = [SETUP.Component.FillHandle;fillHand];
            SETUP.Component.FillComps           = compInd;
        end
        SETUP.Component.FillConn            = connData;
        set(gca,'NextPlot','replace');
        %=================================================
        %=================================================
        % Add a UCS to Fig
        mval    = max([max(GEOMETRY.x)-min(GEOMETRY.x) max(GEOMETRY.y)-min(GEOMETRY.y) max(GEOMETRY.z)-min(GEOMETRY.z)]);
        scl=.075;
        ucs=[0 0 0;
            [1 0 0]*mval*scl;
            [0 1 0]*mval*scl;
            [0 0 1]*mval*scl;
            NaN NaN NaN];
        conn=[2 1 3 5 4 1];
        ucs_handle=line(ucs(conn,1),ucs(conn,2),ucs(conn,3),'Erasemode','normal','Color',SETUP.Colors.UCS,'Tag','Axis:UCS');
        str={'X','Y','Z'};
        for ii=1:3
            t_hand(1,ii)=text(ucs(ii+1,1),ucs(ii+1,2),ucs(ii+1,3),str{ii});
            set(t_hand(1,ii),'Color',[.1 .1 1],'erasemode','normal','Fontsize',7,'Tag','Axis:UCS');
        end
1000
1001         % Scale axis to 2*prct in X,Y,& Z
1002         axis equal;
1003         ax=axis;
1004         prct=0.02;
1005         axis([ax(1)-(ax(2)-ax(1))*prct ax(2)+(ax(2)-ax(1))*prct,...
1006             ax(3)-(ax(4)-ax(3))*prct ax(4)+(ax(4)-ax(3))*prct,...
1007             ax(5)-(ax(6)-ax(5))*prct ax(6)+(ax(6)-ax(5))*prct])
1008
1009         UDATA.Handles.Markers   = DATA.Point;
1010         UDATA.Handles.Labels    = DATA.Text;
1011         UDATA.Handles.Conn      = conn_handle;
1012         UDATA.Handles.Static    = static_handle;
1013         UDATA.Handles.UCS       = [ucs_handle t_hand];
1014         UDATA.Handles.Wire      = SETUP.Component.WireHandle;
1015         UDATA.Handles.Mark      = SETUP.Component.MarkHandle;
1016         UDATA.Handles.Fill      = SETUP.Component.FillHandle;
1017         UDATA.Geometry          = DATA.Plot;
1018         UDATA.Text              = labelText;
1019         UDATA.ActiveFrame       = 1;
1020         UDATA.Direction         = 1;
1021         UDATA.Frames            = SETUP.Animation.Frames;
1022
1023         command('on/off','Labels');
1024         command('on/off','Markers');
1025         command('on/off','Static');
1026         command('on/off','UCS');
1027         set(aniAxis,'CameraViewAngleMode','manual');
1028         command('MultipleChange',SETUP.View.UpVector);
1029         warning on;
1030
1031     case 'changeView'  %===================================================
1032         if nargin==1
1033             value   = SETUP.View.Axis;
1034         else
1035             value   = varargin{1};
1036         end
1037         SETUP.View.Axis = value;
1038         switch value
1039             case 'X'
1040                 val = [1 0 0 0];
1041                 [VWS,CUV] = viewSetup(3,1,SETUP.View.UpVector);
1042                 view(aniAxis,VWS)
1043             case 'Y'
1044                 val = [0 1 0 0];
1045                 [VWS,CUV] = viewSetup(2,1,SETUP.View.UpVector);
1046                 view(aniAxis,VWS)
1047             case 'Z'
1048                 val = [0 0 1 0];
1049                 [VWS,CUV] = viewSetup(1,1,SETUP.View.UpVector);
1050                 set(aniAxis,'View',VWS);
1051             case 'Ortho'
1052                 val = [0 0 0 1];
1053                 [VWS,CUV] = viewSetup(1,2,SETUP.View.UpVector);
1054                 set(aniAxis,'View',[135 35],'CameraUpVector',CUV);
1055         end
1056         switch SETUP.View.Type
1057             case 'Cross-eyed'
1058                 ortho11 = findobj(aniFig,'Tag','Axes:Ortho11');
1059                 switch value
1060                     case {'X','Y','Z'}
1061                         view(ortho11,VWS);
1062                         camorbit(ortho11, SETUP.View.CrosseyeAngle,0,'camera',SETUP.View.UpVector(2))
1063                         camorbit(aniAxis,-SETUP.View.CrosseyeAngle,0,'camera',SETUP.View.UpVector(2))
1064                     otherwise
1065                         set(ortho11,'View',[135 35],'CameraUpVector',CUV);
1066                         camorbit(ortho11, SETUP.View.CrosseyeAngle,0,'camera',SETUP.View.UpVector(2))
1067                         camorbit(aniAxis,-SETUP.View.CrosseyeAngle,0,'camera',SETUP.View.UpVector(2))
1068                 end
1069             case 'Red/Blue Glasses'
1070                 command('updateRotate')
1071         end
1072         str     = {'off','on'};
1073         uiStr   = {'X';'Y';'Z';'Ortho'};
1074         for ii=1:4;
1075             set(findobj(aniFig,'tag',['ContextMenu\Axes\' uiStr{ii}])   ,'Checked',str{val(ii)+1});
1076             set(findobj(aniFig,'tag',['Menu:View:' uiStr{ii}])          ,'Checked',str{val(ii)+1});
1077         end
1078         if nargin<3;command('updatePrefs');end
1079
1080
1081     case 'close'
1082         switch varargin{1}
1083             case 'main'
1084                 resp    = questdlg('Exit Animation?','Animation','Yes','No','No');
1085                 if strcmp(resp,'No')
1086                     return;
1087                 end
1088                 set(findobj(aniFig,'Tag','Toggle:Animate'),'Value',0);
1089                 command('close','preferences');
1090                 command('close','about');
1091                 command('close','components');
1092                 delete(aniFig);
1093             case 'components'
1094                 compFig = findobj(0,'Tag','ANIMATE:COMPONENTS');
1095                 SETUP.Component.Open    = 0;
1096                 if ~isempty(UDATA.Handles)
1097                     set(UDATA.Handles.Conn,'Visible','on');
1098                     command('components','visible',[1:size(SETUP.Component.Name,1)],0);
1099                     command('components','fill'   ,[1:size(SETUP.Component.Name,1)],0);
1100                     if SETUP.Display.Labels
1101                         set(UDATA.Handles.Labels,'Visible','on');
1102                     end
1103                     if SETUP.Display.Markers
1104                         set(UDATA.Handles.Markers,'Visible','on');
1105                     end
1106                 end
1107                 set(findobj(aniFig,'Tag','Menu:View:RedBlue'),'Enable','on');
1108                 delete(compFig);
1109             case 'preferences'
1110                 prefFig = findobj(0,'Tag','ANIMATE:PREFERENCES');
1111                 delete(prefFig);
1112             case 'about'
1113                 abtFig  = findobj(0,'Tag','ANIMATE:ABOUT');
1114                 delete(abtFig);
1115         end
1116
1117
1118     case 'resize'
1119         RESIZE.FigPos=get(aniFig,'Position');
1120         POS=get(aniFig,'Position');
1121         dy=POS(4)-RESIZE.FigPos(4);
1122         x =POS(3);
1123         objects=findobj(aniFig,'Type','uicontrol');
1124         for ii=1:length(objects);
1125             pos=get(objects(ii),'Position');
1126             if strcmp(get(objects(ii),'Tag'),'Frame:Controls')
1127                 set(objects(ii),'Position',[pos(1), pos(2)+dy, x+2 pos(4)]);
1128             else
1129                 set(objects(ii),'Position',[pos(1), pos(2)+dy, pos(3) pos(4)]);
1130             end
1131         end
1132         RESIZE.FigPos=get(aniFig,'Position');
1133         if strcmp(SETUP.View.Type,'Quad');
1134             set(aniAxis,'Units','pixels','Position',[20, 20, POS(3)-70, POS(4)-125]);
1135             set(findobj(aniFig,'Tag','Axes:Ortho11'),'Units','pixels','Position',[20, 20+(POS(4)-125)/2, (POS(3)-70)/2, (POS(4)-125)/2]);
1136             set(findobj(aniFig,'Tag','Axes:Ortho21'),'Units','pixels','Position',[20, 20, (POS(3)-70)/2, (POS(4)-125)/2]);
1137             set(findobj(aniFig,'Tag','Axes:Ortho22'),'Units','pixels','Position',[25+(POS(3))/2, 20, (POS(3)-70)/2, (POS(4)-125)/2]);
1138             set(aniAxis,'Units','pixels','Position',[25+(POS(3))/2, 20+(POS(4)-125)/2, (POS(3)-70)/2, (POS(4)-125)/2]);
1139         elseif strcmp(SETUP.View.Type,'Cross-eyed');
1140             set(findobj(aniFig,'Tag','Axes:Ortho11'),'Units','pixels','Position',[20, 20, (POS(3)-70)/2, (POS(4)-125)]);
1141             set(aniAxis,'Units','pixels','Position',[25+(POS(3))/2, 20, (POS(3)-70)/2, (POS(4)-125)]);
1142
1143         elseif strcmp(SETUP.View.Type,'Red/Blue Glasses');
1144             set(findobj(aniFig,'Tag','Axes:Ortho11'),'Units','pixels','Position',[15, 20, POS(3)-70, POS(4)-125]);
1145             set(aniAxis,'Units','pixels','Position',[25, 20, POS(3)-70, POS(4)-125]);
1146
1147         else
1148             set(aniAxis,'Units','pixels','Position',[20, 20, POS(3)-70, POS(4)-125]);
1149         end
1150
1151     case 'recentFile'
1152         ii=varargin{1};
1153         command('Load',eval(['SETUP.RecentFiles.Type' ii]),eval(['SETUP.RecentFiles.File' ii]),str2num(ii));
1154
1155     case 'Load'
1156         if all([~strcmp(SETUP.View.Type,'Single'),~isempty(GEOMETRY)])
1157             quadTemp    = SETUP.View.Type;
1158             command('viewType','Single');
1159         else
1160             quadTemp    = [];
1161         end
1162         if ishandle(findobj(0,'Tag','ANIMATE:COMPONENTS'))
1163             compTemp    = 1;
1164             compPos     = get(findobj(0,'Tag','ANIMATE:COMPONENTS'),'Position');
1165             command('close','components');
1166             SETUP.Component.Open    = 0;
1167         else
1168             compTemp    = 0;
1169         end
1170         if ismember(SETUP.Colors.Background,[0 0 0],'rows')
1171             clrTable = [1 1 1;1 1 1];
1172         elseif ismember(SETUP.Colors.Background,[1 1 1],'rows')
1173             clrTable = [0 0 0;0 0 0];
1174         else
1175             clrTable = [0 0 0;1 1 1];
1176         end
1177         clrTable    = [clrTable;1 0 0;0 1 0;0 0 1;0 1 1;1 0 1;1 1 0];
1178         switch varargin{1}
1179             case 'Matlab'
1180                 errFlg  = [];
1181                 if nargin==2
1182                     [file,path]=uigetfile(fullfile(SETUP.Path.Data,'*.mat'),'Select data file...');
1183                     if any([file==0,path==0]);
1184                         return;
1185                     end
1186                     file    = fullfile(path,file);
1187                 else
1188                     file    = varargin{2};
1189                 end
1190                 if ~exist(file,'file')
1191                     errordlg('Error finding file.','Animation');
1192                     return
1193                 end
1194                 try
1195                     D   = load(file,'-mat');
1196                 catch
1197                     errFlg{1}   = 'Error loading file.';
1198                     errFlg{2}   = lasterr;
1199                 end
1200                 try
1201                     GEOMETRY    = D.GEOMETRY;
1202                     M           = D.MODAL;
1203                 catch
1204                     errFlg{1}   = 'Invalid animation file.';
1205                     errFlg{2}   = lasterr;
1206                 end
1207                 if ~isempty(errFlg)
1208                     errordlg(errFlg,'Animation');
1209                     return
1210                 end
1211                 set(findobj(aniFig,'Tag','Text:LoadGeom'),'String',file);
1212
1213                 % VECTORS
1214                 ModalNodes  = M(1).Node;
1215                 temp        = 1:length(GEOMETRY.node);
1216                 ind1        = temp(ismember(GEOMETRY.node,unique(GEOMETRY.conn(~isnan(GEOMETRY.conn)))));
1217                 GeomNodes   = GEOMETRY.node(ind1);
1218                 for ii=1:length(GeomNodes)
1219                     ind(ii,1)=find(GeomNodes(ii)==ModalNodes);
1220                 end
1221                 [Y,FreqInd]=sort(imag([M.Freq]));
1222                 for ii=1:length(M);
1223                     MODAL(ii).Freq  = M(FreqInd(ii)).Freq;
1224                     MODAL(ii).Data  = [M(FreqInd(ii)).X(ind) M(FreqInd(ii)).Y(ind) M(FreqInd(ii)).Z(ind)];
1225                     MODAL(ii).Nodes = ModalNodes(ind);
1226                     str{ii,1}       = sprintf('(%02d) %8.3f',ii,2*pi*poles2fz(MODAL(ii).Freq));  % Bugfix 2018-05-10 to print actual undamped natural frequency in 'Mode List'
1227                 end
1228                 [Path,File,Ext]         = fileparts(file);
1229                 SETUP.Path.Data         = Path;
1230                 SETUP.Path.ModalFile    = [File,Ext];
1231                 SETUP.Animation.ModeNr  = 1;
1232                 set(findobj(aniFig,'Tag','Text:LoadVectors'),'String',file);
1233                 set(findobj(aniFig,'Tag','popup_modeList')  ,'Value',1,'String',str,'Enable','on');
1234                 UFF = createUFF(GEOMETRY,MODAL,SETUP,UFF);
1235                 SETUP.Component.Name    = {'None'};
1236                 SETUP.Component.Color   = [0 0 0];
1237                 SETUP.Component.Nodes   = {GEOMETRY.conn};
1238                 SETUP.Component.Visible = 1;
1239                 SETUP.Component.Fill    = 0;
1240
1241             case 'UFF'
1242                 errFlg      = [];
1243                 if nargin==2
1244                     [file,path] =uigetfile(fullfile(SETUP.Path.Data,'*.u*'),'Select UF file...');
1245                     if any([file==0,path==0]);
1246                         return;
1247                     end
1248                     file    = fullfile(path,file);
1249                 else
1250                     file    = varargin{2};
1251                 end
1252                 if ~exist(file,'file')
1253                     errordlg('Error finding file.','Animation');
1254                     return
1255                 end
1256
1257                 try
1258                     [U,dsn] = ufrw('load',file);
1259                 catch
1260                     errFlg  = 'Invalid universal file.';
1261                 end
1262                 if ~isempty(errFlg)
1263                     errordlg(errFlg,'Animation');
1264                     return
1265                 end
1266                 modeGroups  = find(dsn==55);
1267                 geom        = find(dsn==15);
1268                 conn        = find(dsn==82);
1269                 if isempty(modeGroups)
1270                     errFlg{end+1,1}   = 'File contains no mode groups (DSN 55).';
1271                 end
1272                 if isempty(geom)
1273                     errFlg{end+1,1}   = 'File contains no geometry (DSN 15).';
1274                 end
1275                 if isempty(conn)
1276                     errFlg{end+1,1}   = 'File contains no wireframe (DSN 82).';
1277                 end
1278                 if ~isempty(errFlg)
1279                     errordlg(errFlg,'Animation');
1280                     return
1281                 end
1282                 GEOMETRY    = [];
1283                 MODAL       = [];
1284                 UFF.DATA    = U;
1285                 UFF.dsn15   = geom;
1286                 UFF.dsn18   = find(dsn==18);
1287                 UFF.dsn55   = modeGroups;
1288                 UFF.dsn82   = conn;
1289                 UFF.dsn151  = find(dsn==151);
1290                 UFF.dsn164  = find(dsn==164);
1291                 ref18   = [];
1292                 for ii=1:length(UFF.dsn18)
1293                     ref18(ii)       = U{UFF.dsn18(ii)}.CS.Number;
1294                     org             = U{UFF.dsn18(ii)}.CS.Origin;
1295                     xax             = U{UFF.dsn18(ii)}.CS.Xaxis;
1296                     xzp             = U{UFF.dsn18(ii)}.CS.XZplane;
1297                     X               = (xax-org)./norm((xax-org));
1298                     XZp             = (xzp-org)./norm((xzp-org));
1299                     Y               =-cross(X,XZp)./norm(cross(X,XZp));
1300                     Z               = cross(X,Y);
1301                     Tx(:,:,ii)      = [X;Y;Z];
1302                     %TxOrg(:,:,ii)   = Tx(:,:,ii);
1303                     CSType(ii,1)    = U{UFF.dsn18(ii)}.CS.Type;
1304                     CSOffset(ii,:)  = org;
1305                     Xaxis(ii,:)     = xax;
1306                     XZplane(ii,:)   = xzp;
1307                 end
1308
1309                 for ii=1:length(U{geom}.Node)
1310                     if U{geom}.Node(ii).defCS>0
1311                         % Cylidrical
1312                         ind  = min(find(ref18==U{geom}.Node(ii).defCS));
1313                         if isempty(ind)
1314                             warndlg(sprintf('Refernce CS : %d not found.\nNode : %d is in global.',U{geom}.Node(ii).defCS,U{geom}.Node(ii).Label),'Universal file...');
1315                             x   = U{geom}.Node(ii).Crd(1);
1316                             y   = U{geom}.Node(ii).Crd(2);
1317                             z   = U{geom}.Node(ii).Crd(3);
1318                         else
1319                             if CSType(ind,1)==1
1320                                 % Cylindrical
1321                                 % ASSUME THAT DEF IS R, THETA, Z;
1322                                 theta   = U{geom}.Node(ii).Crd(2)*pi/180;
1323                                 tx      = [cos(theta) sin(theta) 0;-sin(theta) cos(theta) 0;0 0 1];
1324                                 x   = U{geom}.Node(ii).Crd(1)*cos(theta);
1325                                 y   = U{geom}.Node(ii).Crd(1)*sin(theta);
1326                                 z   = U{geom}.Node(ii).Crd(3);
1327                                 val = [x y z]*Tx(:,:,ind);
1328                                 x   = val(1);
1329                                 y   = val(2);
1330                                 z   = val(3);
1331                             else
1332                                 % Spherical
1333                             end
1334                         end
1335                     else
1336                         x   = U{geom}.Node(ii).Crd(1);
1337                         y   = U{geom}.Node(ii).Crd(2);
1338                         z   = U{geom}.Node(ii).Crd(3);
1339                     end
1340                     GEOMETRY.node(ii)  = U{geom}.Node(ii).Label;
1341                     GEOMETRY.x(ii)     = x;
1342                     GEOMETRY.y(ii)     = y;
1343                     GEOMETRY.z(ii)     = z;
1344                     if U{geom}.Node(ii).dispCS>0 & ~isempty(ref18)
1345                         ind  = min(find(ref18==U{geom}.Node(ii).dispCS));
1346                         if isempty(ind)
1347                             warndlg(sprintf('Cannot find dsn18 ref for dispCS "%d" : Node "%d"\nDefault is global.',U{geom}.Node(ii).dispCS,U{geom}.Node(ii).Label))
1348                             GEOMETRY.Tx(:,:,ii)  = eye(3);
1349                         else
1350                             GEOMETRY.Tx(:,:,ii)  = tx*Tx(:,:,ind);
1351                         end
1352                     else
1353                         GEOMETRY.Tx(:,:,ii)  = eye(3);
1354                     end
1355                 end
1356                 CONN=[];
1357                 dmy = 0;
1358                 for ii=1:length(conn)
1359                     temp=U{conn(ii)}.Trace;
1360                     temp(find(temp==-1))    = NaN;
1361                     temp(find(temp== 0))    = NaN;
1362                     if ~isempty(temp)
1363                         dmy = dmy+1;
1364                         CONN        = [CONN temp NaN];
1365                         CNN{dmy,1}  = [temp NaN];
1366                         while U{conn(ii)}.Color+1>8
1367                             U{conn(ii)}.Color   = U{conn(ii)}.Color-8;
1368                         end
1369                         CLR(dmy,:)  = clrTable(U{conn(ii)}.Color+1,:);
1370                         NAME{dmy,1} = U{conn(ii)}.ID;
1371                     end
1372                 end
1373                 GEOMETRY.conn=CONN;
1374                 % group by components
1375                 unames  = unique(NAME);
1376                 SETUP.Component.Name    = NAME;
1377                 SETUP.Component.Color   = CLR;
1378                 SETUP.Component.Nodes   = CNN;
1379                 SETUP.Component.Visible = ones(size(CNN,1),1);
1380                 SETUP.Component.Fill    = zeros(size(CNN,1),1);
1381
1382                 NrPts   = length([U{modeGroups(1)}.Node.Num]);
1383                 for ii=1:length(modeGroups)
1384                     freq(ii,1)  = U{modeGroups(ii)}.Real(2);
1385                 end
1386                 indPos  = find(freq>0);
1387                 MODAL   = [];
1388                 for ii=1:length(indPos)
1389                     Data   = reshape([U{modeGroups(indPos(ii))}.Node.Data],3,NrPts)';
1390                     MODAL(ii).Node  = [U{modeGroups(indPos(ii))}.Node.Num]';
1391                     for nn=1:size(Data,1)
1392                         ind  = find(MODAL(ii).Node(nn)==GEOMETRY.node);
1393                         if ~isempty(ind)
1394                             Data(nn,:)   = Data(nn,:)*GEOMETRY.Tx(:,:,ind);
1395                         end
1396                     end
1397                     MODAL(ii).X     = Data(:,1);
1398                     MODAL(ii).Y     = Data(:,2);
1399                     MODAL(ii).Z     = Data(:,3);
1400                     MODAL(ii).Freq  = [U{modeGroups(indPos(ii))}.Real(1)+j*U{modeGroups(indPos(ii))}.Real(2)]./2/pi;
1401                 end
1402                 M           = MODAL;
1403                 ModalNodes  = M(1).Node;
1404                 temp        = 1:length(GEOMETRY.node);
1405                 ind1        = temp(ismember(GEOMETRY.node,unique(GEOMETRY.conn(~isnan(GEOMETRY.conn)))));
1406                 GeomNodes   = GEOMETRY.node(ind1);
1407                 for ii=1:length(GeomNodes)
1408                     ind(ii,1)=find(GeomNodes(ii)==ModalNodes);
1409                 end
1410                 [Y,FreqInd]=sort(imag([M.Freq]));
1411                 for ii=1:length(M);
1412                     MODAL(ii).Freq  = M(FreqInd(ii)).Freq;
1413                     MODAL(ii).Data  = [M(FreqInd(ii)).X(ind) M(FreqInd(ii)).Y(ind) M(FreqInd(ii)).Z(ind)];
1414                     MODAL(ii).Nodes = ModalNodes(ind);
1415                     str{ii,1}       = sprintf('(%02d) %8.3f',ii,imag(MODAL(ii).Freq));
1416                 end
1417                 set(findobj(aniFig,'Tag','popup_modeList'),'Value',1,'String',str,'Enable','on');
1418                 [Path,File,Ext]         = fileparts(file);
1419                 SETUP.Path.Data         = Path;
1420                 SETUP.Path.ModalFile    = [File,Ext];
1421                 SETUP.Animation.ModeNr  = 1;
1422                 set(findobj(aniFig,'Tag','Menu:Display:Components'),'Enable','on');
1423         end
1424         command('geo/con');
1425         command('update_mode');
1426         set(findobj(aniFig,'Tag','Toggle:Animate')  ,'Enable','on');
1427         set(findobj(aniFig,'Tag','Toggle:Zoom')     ,'Enable','on');
1428         set(findobj(aniFig,'Tag','Toggle:Rotate')   ,'Enable','on');
1429         set(findobj(aniFig,'Tag','Menu:Display')    ,'Enable','on');
1430         set(findobj(aniFig,'Tag','Menu:View')       ,'Enable','on');
1431         set(findobj(aniFig,'Tag','Menu:File:Save')  ,'Enable','on');
1432         if ~isempty(quadTemp)
1433             command('viewType',quadTemp)
1434         end
1435         if compTemp & strcmp(varargin{1},'UFF')
1436             command('components','init',compPos);
1437         end
1438         SETUP   = updateRecentFiles(aniFig,file,varargin{1},SETUP);
1439         defaults('addRecentFiles',SETUP);
1440         set(findobj(aniFig,'Tag','Toggle:Animate'),'Value',1);
1441         command('run_animate');
1442
1443     case 'update_mode'
1444         val=get(findobj(aniFig,'Tag','popup_modeList'),'Value');
1445         SETUP.Animation.ModeNr=val;
1446         if imag(MODAL(val).Freq)>0
1447             SIGN='-';
1448         else
1449             SIGN='+';
1450         end
1451         str=sprintf('%s\nMode Nr: %02d\nFreq (Hz): %8.3f% 1s%8.3fi',SETUP.Path.ModalFile,val,real(MODAL(val).Freq),SIGN,abs(imag(MODAL(val).Freq)));
1452         set(findobj(aniFig,'Tag','Text:Annotate'),'String',str);
1453         command('reset_animation');
1454
1455
1456     case 'set_vectorType'
1457         val=get(findobj(aniFig,'Tag','Popup:vectorType'),'Value');
1458         str=get(findobj(aniFig,'Tag','Popup:vectorType'),'String');
1459         SETUP.View.VectorType=str{val};
1460         command('update_mode');
1461         if nargin<3;command('updatePrefs');end
1462 end  % End Switch(action)
1463
1464 %==========================================================================
1465 function [VWS,CUV] = viewSetup(pV,pC,upVector)
1466 T       = eye(3);
1467 str     = {'+X','+Y','+Z'};
1468 vw      = [90,0;0,0;0,90];
1469 vw(:,:,1)   = [90 0;180 0;0 90];
1470 vw(:,:,2)   = [180 0;0 90;90 0];
1471 vw(:,:,3)   = [180 90;90 0;180 0];
1472 vals    = [1 2 3;2 3 1;3 1 2];
1473 VWS     = vw(:,:,find(ismember(str,upVector)));
1474
1475 % GCA Camera Up Values
1476 cuv(:,:,1)  = [0 -1 0;1 0 0; 1  0  0;1 0 0]; % +X Up view
1477 cuv(:,:,2)  = [0 0 -1;0 1 0; 0 1  0;0 1 0]; % +Y Up view
1478 cuv(:,:,3)  = [-1 0 0;0 0 1; 0 0 1;0 0 1]; % +Z Up view
1479 CUV         = cuv(:,:,find(ismember(str,upVector)));
1480
1481 VWS = VWS(pV,:);
1482 CUV = CUV(pC,:);
1483
1484
1485 %==========================================================================
1486 function [ANI,Nodes]=set_mode(vector)
1487 global UDATA SETUP MODAL
1488 aniFig          = findobj(0,'Tag','ANIMATE');
1489 aniAxis         = findobj(aniFig,'Tag','Axes:Single');
1490 UDATA.Frames    = SETUP.Animation.Frames;
1491
1492 if UDATA.ActiveFrame>UDATA.Frames
1493    UDATA.ActiveFrame=ceil(UDATA.Frames/2);
1494 end
1495
1496 msx=[vector.x;NaN];
1497 msy=[vector.y;NaN];
1498 msz=[vector.z;NaN];
1499 switch SETUP.View.VectorType
1500 case 'Real'
1501     msx=real(msx);
1502     msy=real(msy);
1503     msz=real(msz);
1504
1505 case 'Imaginary'
1506     msx=imag(msx);
1507     msy=imag(msy);
1508     msz=imag(msz);
1509
1510 end
1511 % complex loop from -max to +max with a phase difference added
1512 temp.X=vecompspace(abs(msx),angle(msx),UDATA.Frames)+UDATA.Geometry(:,1)*ones(1,UDATA.Frames);
1513 temp.Y=vecompspace(abs(msy),angle(msy),UDATA.Frames)+UDATA.Geometry(:,2)*ones(1,UDATA.Frames);
1514 temp.Z=vecompspace(abs(msz),angle(msz),UDATA.Frames)+UDATA.Geometry(:,3)*ones(1,UDATA.Frames);
1515
1516 xx  = abs(temp.X(1:end-1,:)-UDATA.Geometry(1:end-1,1)*ones(1,UDATA.Frames));
1517 yy  = abs(temp.Y(1:end-1,:)-UDATA.Geometry(1:end-1,1)*ones(1,UDATA.Frames));
1518 zz  = abs(temp.Z(1:end-1,:)-UDATA.Geometry(1:end-1,1)*ones(1,UDATA.Frames));
1519 a   = sqrt(sum(xx.^2+yy.^2+zz.^2,1));
1520 ind = find(a==max(a));
1521 SETUP.Animation.MaxFrame    = min(ind);
1522
1523 for fr=1:UDATA.Frames
1524    Nodes(:,1:3,fr)      = [temp.X(1:end-1,fr) temp.Y(1:end-1,fr) temp.Z(1:end-1,fr)];
1525    CompNodes(:,1:3,fr)  = [[temp.X(1:end-1,fr);NaN] [temp.Y(1:end-1,fr);NaN] [temp.Z(1:end-1,fr);NaN]];
1526    ANI(1,fr).X          = temp.X(UDATA.ConnList,fr);
1527    ANI(1,fr).Y          = temp.Y(UDATA.ConnList,fr);
1528    ANI(1,fr).Z          = temp.Z(UDATA.ConnList,fr);
1529 end
1530 NUDATA.ANI      = ANI;
1531 NUDATA.NODES    = Nodes;
1532 NUDATA.CompNodes= CompNodes;
1533
1534 set(aniAxis,'Userdata',NUDATA);
1535
1536
1537 %==========================================================================
1538 function HAND = getHandles(pos,ax,HAND,varargin);
1539 if nargin>3
1540     HAND.Conn       = findobj(ax,'Tag','Axis:Shape');
1541     HAND.Static     = findobj(ax,'Tag','Axis:Static');
1542     HAND.Markers    = findobj(ax,'Tag','Axis:Node');
1543     HAND.UCS        = findobj(ax,'Tag','Axis:UCS');
1544     HAND.Labels     = findobj(ax,'Tag','Axis:Label');
1545     HAND.Wire       = flipud(findobj(ax,'Tag','Axis:Wire'));
1546     HAND.Mark       = flipud(findobj(ax,'Tag','Axis:Mark'));
1547     HAND.Fill       = flipud(findobj(ax,'Tag','Axis:Fill'));
1548 else
1549     HAND.Conn(pos)      = findobj(ax,'Tag','Axis:Shape');
1550     HAND.Static(pos)    = findobj(ax,'Tag','Axis:Static');
1551     HAND.Markers(pos)   = findobj(ax,'Tag','Axis:Node');
1552     HAND.UCS(pos,:)     = findobj(ax,'Tag','Axis:UCS');
1553     HAND.Labels(:,pos)  = findobj(ax,'Tag','Axis:Label');
1554     HAND.Wire(:,pos)    = flipud(findobj(ax,'Tag','Axis:Wire'));
1555     HAND.Mark(:,pos)    = flipud(findobj(ax,'Tag','Axis:Mark'));
1556     HAND.Fill(:,pos)    = flipud(findobj(ax,'Tag','Axis:Fill'));
1557 end
1558
1559 %==========================================================================
1560 function SETUP = updateRecentFiles(aniFig,file,type,SETUP);
1561 files   = {SETUP.RecentFiles.File1;SETUP.RecentFiles.File2;SETUP.RecentFiles.File3;SETUP.RecentFiles.File4};
1562 ind     = find(ismember(files,file));
1563 if isempty(ind)
1564     SETUP.RecentFiles.File4 = SETUP.RecentFiles.File3;
1565     SETUP.RecentFiles.Type4 = SETUP.RecentFiles.Type3;
1566     SETUP.RecentFiles.File3 = SETUP.RecentFiles.File2;
1567     SETUP.RecentFiles.Type3 = SETUP.RecentFiles.Type2;
1568     SETUP.RecentFiles.File2 = SETUP.RecentFiles.File1;
1569     SETUP.RecentFiles.Type2 = SETUP.RecentFiles.Type1;
1570     SETUP.RecentFiles.File1 = file;
1571     SETUP.RecentFiles.Type1 = type;
1572 else
1573     temp    = SETUP.RecentFiles;
1574     rest    = setdiff([1:4],ind);
1575     for ii=3:-1:1;
1576         eval(['SETUP.RecentFiles.File' num2str(ii+1) '= temp.File' num2str(rest(ii)) ';']);
1577         eval(['SETUP.RecentFiles.Type' num2str(ii+1) '= temp.Type' num2str(rest(ii)) ';']);
1578     end
1579     SETUP.RecentFiles.File1 = eval(['temp.File' num2str(ind) ';']);
1580     SETUP.RecentFiles.Type1 = eval(['temp.Type' num2str(ind) ';']);
1581 end
1582
1583 str = {'on','off'};
1584 [p,fileTemp,e]  = fileparts(SETUP.RecentFiles.File1);
1585 set(findobj(aniFig,'Tag','Menu:File:File1'),'Label',[fileTemp,e],'Visible',str{isempty(SETUP.RecentFiles.File1)+1});
1586 [p,fileTemp,e]  = fileparts(SETUP.RecentFiles.File2);
1587 set(findobj(aniFig,'Tag','Menu:File:File2'),'Label',[fileTemp,e],'Visible',str{isempty(SETUP.RecentFiles.File2)+1});
1588 [p,fileTemp,e]  = fileparts(SETUP.RecentFiles.File3);
1589 set(findobj(aniFig,'Tag','Menu:File:File3'),'Label',[fileTemp,e],'Visible',str{isempty(SETUP.RecentFiles.File3)+1});
1590 [p,fileTemp,e]  = fileparts(SETUP.RecentFiles.File4);
1591 set(findobj(aniFig,'Tag','Menu:File:File4'),'Label',[fileTemp,e],'Visible',str{isempty(SETUP.RecentFiles.File4)+1});
1592
1593 %==========================================================================
1594 function clr = getColor(default,msg);
1595 clr = uisetcolor(default,msg);
1596 if ismember(clr,default,'rows')
1597     clr = [];
1598 end
1599
1600 %==========================================================================
1601 function updatePrefs(action,dlg,TEMP)
1602 set(findobj(dlg,'Tag','Preferences:AutoApply'),'Value',TEMP.Animation.AutoApplyPrefs);
1603 switch action
1604     case 'all'
1605         updatePrefs('animation' ,dlg,TEMP)
1606         updatePrefs('display'   ,dlg,TEMP)
1607         updatePrefs('view'      ,dlg,TEMP)
1608         updatePrefs('color'     ,dlg,TEMP)
1609
1610     case 'animation'
1611         set(findobj(dlg,'Tag','Preferences:FPC'),'String',num2str(TEMP.Animation.Frames));
1612         set(findobj(dlg,'Tag','Preferences:Amp'),'String',num2str(TEMP.Animation.Amplitude));
1613         set(findobj(dlg,'Tag','Preferences:Deg'),'String',num2str(TEMP.Animation.Theta));
1614     case 'display'
1615         set(findobj(dlg,'Tag','Preferences:Annotate'),'Value',TEMP.Display.Annotate);
1616         set(findobj(dlg,'Tag','Preferences:Static')  ,'Value',TEMP.Display.Static);
1617         set(findobj(dlg,'Tag','Preferences:Markers') ,'Value',TEMP.Display.Markers);
1618         set(findobj(dlg,'Tag','Preferences:Labels')  ,'Value',TEMP.Display.Labels);
1619         set(findobj(dlg,'Tag','Preferences:UCS')     ,'Value',TEMP.Display.UCS);
1620         set(findobj(dlg,'Tag','Preferences:Spin')    ,'Value',TEMP.Display.Spin);
1621     case 'view'
1622         str = get(findobj(dlg,'Tag','Preferences:Axis'),'String');
1623         val = find(ismember(str,TEMP.View.Axis));
1624         set(findobj(dlg,'Tag','Preferences:Axis'),'Value',val);
1625         str = {'Single','Quad','Cross-eyed','Red/Blue Glasses'};
1626         val = find(ismember(str,TEMP.View.Type));
1627         set(findobj(dlg,'Tag','Preferences:Type'),'Value',val);
1628         str = get(findobj(dlg,'Tag','Preferences:UpVector'),'String');
1629         val = find(ismember(str,TEMP.View.UpVector));
1630         set(findobj(dlg,'Tag','Preferences:UpVector'),'Value',val);
1631         str = get(findobj(dlg,'Tag','Preferences:VectorType'),'String');
1632         val = find(ismember(str,TEMP.View.VectorType));
1633         set(findobj(dlg,'Tag','Preferences:VectorType'),'Value',val);
1634     case 'color'
1635         set(findobj(dlg,'Tag','Preferences:BackgroundColor') ,'BackgroundColor',TEMP.Colors.Background,'ForegroundColor',TEMP.Colors.Background);
1636         set(findobj(dlg,'Tag','Preferences:AnnotateColor')   ,'BackgroundColor',TEMP.Colors.Background,'ForegroundColor',TEMP.Colors.Annotate);
1637         set(findobj(dlg,'Tag','Preferences:StaticColor')     ,'BackgroundColor',TEMP.Colors.Background,'ForegroundColor',TEMP.Colors.Static);
1638         set(findobj(dlg,'Tag','Preferences:MarkersColor')    ,'BackgroundColor',TEMP.Colors.Background,'ForegroundColor',TEMP.Colors.Markers);
1639         set(findobj(dlg,'Tag','Preferences:LabelsColor')     ,'BackgroundColor',TEMP.Colors.Background,'ForegroundColor',TEMP.Colors.Labels);
1640         set(findobj(dlg,'Tag','Preferences:ShapeColor')      ,'BackgroundColor',TEMP.Colors.Background,'ForegroundColor',TEMP.Colors.Shape);
1641         set(findobj(dlg,'Tag','Preferences:UCSColor')        ,'BackgroundColor',TEMP.Colors.Background,'ForegroundColor',TEMP.Colors.UCS);
1642         set(findobj(dlg,'Tag','Preferences:RightEyeColor')   ,'BackgroundColor',TEMP.Colors.Background,'ForegroundColor',TEMP.Colors.RightEye);
1643         set(findobj(dlg,'Tag','Preferences:LeftEyeColor')    ,'BackgroundColor',TEMP.Colors.Background,'ForegroundColor',TEMP.Colors.LeftEye);
1644 end
1645
1646 %==========================================================================
1647 function TEMP = getDefaults(TEMP);
1648 TEMP.Version.Nr            = '1.02 beta';
1649 TEMP.Version.Date          = '13-Aug-2005';
1650
1651 TEMP.Display.Annotate      = 1;
1652 TEMP.Display.Static        = 1;
1653 TEMP.Display.Markers       = 0;
1654 TEMP.Display.Labels        = 0;
1655 TEMP.Display.UCS           = 0;
1656 TEMP.Display.Spin          = 0;
1657 TEMP.Display.MaxDeflection = 0;
1658 TEMP.Display.Renderer      = 'zbuffer';
1659 TEMP.Display.Fill = 0;
1660
1661 TEMP.Component.Open        = 0;
1662 TEMP.Component.Wireframe   = 1;
1663 TEMP.Component.Name        = [];
1664 TEMP.Component.Color       = [0 0 0];
1665 TEMP.Component.Visible     = 1;
1666 TEMP.Component.Fill        = 0;
1667
1668 TEMP.Animation.Frames           = 250;
1669 TEMP.Animation.Amplitude        = .25;
1670 TEMP.Animation.Theta            = 30;
1671 TEMP.Animation.MaxFrame         = round(TEMP.Animation.Frames/2);
1672 TEMP.Animation.AutoApplyPrefs   = 0;
1673
1674 TEMP.View.Type              = 'Single';
1675 TEMP.View.Axis              = 'Ortho';
1676 TEMP.View.CrosseyeAngle     = 3;
1677 TEMP.View.VectorType        = 'Complex';
1678 TEMP.View.UpVector          = '+Z';
1679 TEMP.View.MaxDeflection     = 0;
1680
1681 TEMP.Colors.Background  = [ 1   1   1  ];
1682 TEMP.Colors.Annotate    = [ 0   0   0  ];
1683 TEMP.Colors.Static      = [ 1   0   0  ];
1684 TEMP.Colors.Markers     = [ 0   0   0  ];
1685 TEMP.Colors.Labels      = [ 0   0   0  ];
1686 TEMP.Colors.Shape       = [ 0   0   0  ];
1687 TEMP.Colors.UCS         = [ 0.1 0.1 1  ];
1688 TEMP.Colors.RightEye    = [ 1   0   0  ];
1689 TEMP.Colors.LeftEye     = [ 0   1   1  ];
1690
1691 TEMP.AVI.On                = 0;
1692 TEMP.AVI.Start             = 0;
1693 TEMP.AVI.Frame             = 0;
1694 TEMP.AVI.Movie             = [];
1695 TEMP.AVI.Format            = 'Cinepak';
1696 TEMP.AVI.Quality           = 75;
1697 TEMP.AVI.TimeLength        = 1;
1698 TEMP.AVI.DoAllModes        = 0;
1699
1700 TEMP.Snapshot.Format       = 'EMF metafile';
1701 TEMP.Snapshot.Resolution   = 100;
1702 TEMP.Snapshot.Quality      = 75;
1703 TEMP.Snapshot.DoAllModes   = 0;
1704 TEMP.Snapshot.Renderer     = 'Z-buffer';
1705
1706 %==========================================================================
1707 function updateAniFig(aniFig,SETUP,H)
1708 % Display
1709 str = {'off','on'};
1710 set(findobj(aniFig,'Tag','Menu:Display:Annotate')   ,'Checked',str{SETUP.Display.Annotate+1});
1711 set(findobj(aniFig,'Tag','Menu:Display:Static')     ,'Checked',str{SETUP.Display.Static+1});
1712 set(findobj(aniFig,'Tag','Menu:Display:Markers')    ,'Checked',str{SETUP.Display.Markers+1});
1713 set(findobj(aniFig,'Tag','Menu:Display:Labels')     ,'Checked',str{SETUP.Display.Labels+1});
1714 set(findobj(aniFig,'Tag','Menu:Display:UCS')        ,'Checked',str{SETUP.Display.UCS+1});
1715 set(findobj(aniFig,'Tag','Menu:Display:Spin')       ,'Checked',str{SETUP.Display.Spin+1});
1716 % View-Axis
1717 val = ismember({'X','Y','Z','Ortho'},SETUP.View.Axis);
1718 set(findobj(aniFig,'Tag','Menu:View:X')     ,'Checked',str{val(1)+1});
1719 set(findobj(aniFig,'Tag','Menu:View:Y')     ,'Checked',str{val(2)+1});
1720 set(findobj(aniFig,'Tag','Menu:View:Z')     ,'Checked',str{val(3)+1});
1721 set(findobj(aniFig,'Tag','Menu:View:Ortho') ,'Checked',str{val(4)+1});
1722 % ContextMenu-Axis
1723 set(findobj(aniFig,'Tag','ContextMenu\Axes\X')      ,'Checked',str{val(1)+1});
1724 set(findobj(aniFig,'Tag','ContextMenu\Axes\Y')      ,'Checked',str{val(2)+1});
1725 set(findobj(aniFig,'Tag','ContextMenu\Axes\Z')      ,'Checked',str{val(3)+1});
1726 set(findobj(aniFig,'Tag','ContextMenu\Axes\Ortho')  ,'Checked',str{val(4)+1});
1727 % View-Type
1728 val = ismember({'Single','Quad','Cross-eyed','Red/Blue Glasses'},SETUP.View.Type);
1729 set(findobj(aniFig,'Tag','Menu:View:Single')    ,'Checked',str{val(1)+1});
1730 set(findobj(aniFig,'Tag','Menu:View:Quad')      ,'Checked',str{val(2)+1});
1731 set(findobj(aniFig,'Tag','Menu:View:Crosseyed') ,'Checked',str{val(3)+1});
1732 set(findobj(aniFig,'Tag','Menu:View:RedBlue')   ,'Checked',str{val(4)+1});
1733 % View-UpVector
1734 val = ismember({'"X','+Y','+Z'},SETUP.View.UpVector);
1735 set(findobj(aniFig,'Tag','Menu:View:+X'),'Checked',str{val(1)+1});
1736 set(findobj(aniFig,'Tag','Menu:View:+Y'),'Checked',str{val(2)+1});
1737 set(findobj(aniFig,'Tag','Menu:View:+Z'),'Checked',str{val(3)+1});
1738 % View-VectorType
1739 val = ismember({'Real','Imaginary','Complex'},SETUP.View.VectorType);
1740 set(findobj(aniFig,'Tag','Menu:View:Real')      ,'Checked',str{val(1)+1});
1741 set(findobj(aniFig,'Tag','Menu:View:Imaginary') ,'Checked',str{val(2)+1});
1742 set(findobj(aniFig,'Tag','Menu:View:Complex')   ,'Checked',str{val(3)+1});
1743 % Edits&Sliders
1744 set(findobj(aniFig,'Tag','Edit:FPC')    ,'String',num2str(SETUP.Animation.Frames));
1745 set(findobj(aniFig,'Tag','Slider:FPC')  ,'Value' ,SETUP.Animation.Frames);
1746 set(findobj(aniFig,'Tag','Edit:Amp')    ,'String',num2str(SETUP.Animation.Amplitude));
1747 set(findobj(aniFig,'Tag','Slider:Amp')  ,'Value' ,SETUP.Animation.Amplitude);
1748 set(findobj(aniFig,'Tag','Edit:Deg')    ,'String',num2str(SETUP.Animation.Theta));
1749 set(findobj(aniFig,'Tag','Slider:Deg')  ,'Value' ,SETUP.Animation.Theta);
1750
1751 % Fig & Axes
1752 bgc = SETUP.Colors.Background;
1753 set(aniFig,'Color',bgc);
1754 axs = findobj(aniFig,'Type','Axes');
1755 set(findobj(aniFig,'Tag','Text:Annotate'),'ForegroundColor',SETUP.Colors.Annotate,'BackgroundColor',bgc)
1756 for ii=1:length(axs)
1757     set(axs(ii),'Color',bgc,'Xcolor',bgc,'Ycolor',bgc,'Zcolor',bgc);
1758 end
1759 if ~isempty(H)
1760     % Colors -----------------
1761     if strcmp(SETUP.View.Type,'Red/Blue Glasses')
1762         clr = [SETUP.Colors.LeftEye;SETUP.Colors.RightEye];
1763         for ii=1:2
1764             set(H.Static(ii)    ,'Color',clr(ii,:))
1765             set(H.Markers(ii)   ,'Color',clr(ii,:))
1766             set(H.Labels(:,ii)  ,'Color',clr(ii,:))
1767             set(H.UCS(ii)       ,'Color',clr(ii,:))
1768             set(H.Conn(ii)      ,'Color',clr(ii,:))
1769         end
1770     else
1771         set(H.Static    ,'Color',SETUP.Colors.Static)
1772         set(H.Markers   ,'Color',SETUP.Colors.Markers)
1773         set(H.Labels    ,'Color',SETUP.Colors.Labels)
1774         set(H.UCS       ,'Color',SETUP.Colors.UCS)
1775         set(H.Conn      ,'Color',SETUP.Colors.Shape)
1776     end
1777     % Display
1778     command('Change','Annotate' ,SETUP.Display.Annotate,'skip')
1779     command('Change','Static'   ,SETUP.Display.Static,'skip')
1780     command('Change','Markers'  ,SETUP.Display.Markers,'skip')
1781     command('Change','Labels'   ,SETUP.Display.Labels,'skip')
1782     command('Change','UCS'      ,SETUP.Display.UCS,'skip')
1783     command('Change','Spin'     ,SETUP.Display.Spin,'skip')
1784
1785     % View -------------------
1786     command('changeView'    ,SETUP.View.Axis,'skip');
1787     command('viewType'      ,SETUP.View.Type,'skip');
1788     command('MultipleChange',SETUP.View.UpVector,'skip')
1789     command('MultipleChange',SETUP.View.VectorType,'skip')
1790 end
1791
1792 %==========================================================================
1793 function str = compListbox(SETUP);
1794 onStr   = {'off','on'};
1795 for ii=1:size(SETUP.Component.Name)
1796     str{ii,1}   = sprintf('%-10s %3s %3s  [%0.2f %0.2f %0.2f]',SETUP.Component.Name{ii},...
1797         onStr{SETUP.Component.Visible(ii,1)+1},...
1798         onStr{SETUP.Component.Fill(ii,1)+1},...
1799         SETUP.Component.Color(ii,:));
1800 end
1801
1802 %==========================================================================
1803 function UFF = createUFF(GEOMETRY,MODAL,SETUP,UFF);
1804 UFF = [];
1805 % Header (151)
1806 ii  = 1;
1807 UFF.dsn151    = ii;
1808 UFF.DATA{ii,1}.DSN    = 151;
1809 UFF.DATA{ii,1}.UID    = [];
1810 UFF.DATA{ii,1}.Ext    = [];
1811 UFF.DATA{ii,1}.ModelFileName         = SETUP.Path.ModalFile;
1812 UFF.DATA{ii,1}.ModelFileDescription  = 'Modal Vector Animation';
1813 UFF.DATA{ii,1}.ProgramDB     = 'Modal Vector Animation';
1814 UFF.DATA{ii,1}.DateCreated   = datestr(now,1);
1815 UFF.DATA{ii,1}.TimeCreated   = datestr(now,13);
1816 UFF.DATA{ii,1}.Version1      = 0;
1817 UFF.DATA{ii,1}.Version2      = 0;
1818 UFF.DATA{ii,1}.FileType      = 0;
1819 UFF.DATA{ii,1}.DateSaved     = datestr(now,1);
1820 UFF.DATA{ii,1}.TimeSaved     = datestr(now,13);
1821 UFF.DATA{ii,1}.ProgramUF     = 'Modal Vector Animation';
1822 UFF.DATA{ii,1}.DateWritten   = datestr(now,1);
1823 UFF.DATA{ii,1}.TimeWritten   = datestr(now,13);
1824 % Units (164)
1825 ii  = 2;
1826 UFF.dsn164    = ii;
1827 UFF.DATA{ii,1}.DSN               = 164;
1828 UFF.DATA{ii,1}.UID               = [];
1829 UFF.DATA{ii,1}.Ext               = [];
1830 UFF.DATA{ii,1}.UnitsCode         = 9;
1831 UFF.DATA{ii,1}.UnitsDescription  = 'User Defined';
1832 UFF.DATA{ii,1}.TempMode          = 0;
1833 UFF.DATA{ii,1}.Length            = 1;
1834 UFF.DATA{ii,1}.Force             = 1;
1835 UFF.DATA{ii,1}.Temperature       = 1;
1836 UFF.DATA{ii,1}.TemperatureOffset = 0;
1837
1838 % Nodes (15)
1839 ii  = 3;
1840 UFF.dsn15     = ii;
1841 UFF.DATA{ii,1}.DSN    = 15;
1842 UFF.DATA{ii,1}.UID    = [];
1843 UFF.DATA{ii,1}.Ext    = [];
1844 for jj=1:length(GEOMETRY.node)
1845     UFF.DATA{ii,1}.Node(jj,1).Label  = GEOMETRY.node(jj);
1846     UFF.DATA{ii,1}.Node(jj,1).defCS  = 0;
1847     UFF.DATA{ii,1}.Node(jj,1).dispCS = 0;
1848     UFF.DATA{ii,1}.Node(jj,1).Color  = 1;
1849     UFF.DATA{ii,1}.Node(jj,1).Crd    = [GEOMETRY.x(jj) GEOMETRY.y(jj) GEOMETRY.z(jj)];
1850 end
1851
1852 % Wireframe (82)
1853 ii  = 4;
1854 UFF.dsn82     = ii;
1855 UFF.DATA{ii,1}.DSN           = 82;
1856 UFF.DATA{ii,1}.UID           = [];
1857 UFF.DATA{ii,1}.Ext           = [];
1858 UFF.DATA{ii,1}.ID            = 'None';
1859 UFF.DATA{ii,1}.TraceNum      = 1;
1860 UFF.DATA{ii,1}.Color         = 1;
1861 conn                    = GEOMETRY.conn;
1862 conn(find(isnan(conn))) = 0;
1863 conn(find(conn<0))      = 0;
1864 UFF.DATA{ii,1}.Trace         = conn;
1865
1866 % Modes (55)
1867 %MODAL=MODAL(1:7);   % Outcommented 2011-11-03, occasional crash
1868 for modeNr = 1:length(MODAL)
1869     ii  = 4+modeNr;
1870     UFF.DATA{ii,1}.DSN    = 55;
1871     UFF.DATA{ii,1}.UID    = [];
1872     UFF.DATA{ii,1}.Ext    = [];
1873     % 2012-01-13: enhancement: Add freq & damping to ID Line 1 for
1874     % Engineering Office display
1875     UFF.DATA{ii,1}.ID{1,1}=['Freq ' num2str(imag(MODAL(modeNr).Freq)) ', Damp ' num2str(real(MODAL(modeNr).Freq))];
1876     for jj=2:5;
1877         UFF.DATA{ii,1}.ID{jj,1}  = 'None';
1878     end
1879     UFF.DATA{ii,1}.modelType     = 1;
1880     UFF.DATA{ii,1}.analysisType  = 3;
1881     UFF.DATA{ii,1}.dataChar      = 2;
1882     UFF.DATA{ii,1}.specificType  = 8;
1883     UFF.DATA{ii,1}.Int           = [1 modeNr];
1884     UFF.DATA{ii,1}.Real          = [real(MODAL(modeNr).Freq) imag(MODAL(modeNr).Freq) 0 0 0 0]*2*pi;
1885     for node = 1:size(MODAL(1).Nodes,1)
1886         UFF.DATA{ii,1}.Node(node,1).Num  = MODAL(modeNr).Nodes(node);
1887         UFF.DATA{ii,1}.Node(node,1).Data = MODAL(modeNr).Data(node,:);
1888     end
1889 end
1890 UFF.dsn55   = [5:length(UFF.DATA)].';