function set_material_mech( self, faces )

% Koeffizienten fuer Luftphase
specifyCoefficients(self.model,'m',0,'d',0,'c',1/...
    (self.cnfg.material.mu_Luft),'a',0,'f',0,'Face',...
    faces.Luft);       
% Eisenkern und Rotorbuechse
specifyCoefficients(self.model,'m',0,'d',0,'c',1/...
    (self.cnfg.material.mu_Eisen),'a',0,'f',0,'Face',...
    faces.Eisen);       
% Koeffizienten der Kupferspulen
specifyCoefficients(self.model,'m',0,'d',0,'c',1/...
    (self.cnfg.material.mu_Kupfer),'a',0,'f',0,'Face',...
    [faces.SpuleA_1,faces.SpuleB_1,faces.SpuleA_2,...
    faces.SpuleB_2,faces.SpuleA_3,faces.SpuleB_3,...
    faces.SpuleA_4,faces.SpuleB_4]);  
end

